//
//  EnglishText3.swift
//  Eng_shuffle
//
//  Created by tanakat on 2017/06/17.
//  Copyright © 2017年 tanakat0516. All rights reserved.
//

import Foundation


func setSentence3() {

  JpnArray3[0] = "ウィスキーのボトルを2本も空けて車を運転するのは危険だ。"
  JpnArray3.append("交通量の多い通りを、信号が青に変わらないうちに横断するのはとても危険です。")
  JpnArray3.append("早朝、鳥のさえずりを聴きながら散歩するのは本当に気持ちがいい。")
  JpnArray3.append("日本の高校生の大半が、大学入試に備えるため塾に行く。")
  JpnArray3.append("日本人は、エレベーターや信号待ちだと、わずか30秒でいらいらし始める。")
  JpnArray3.append("列車で隣に座ったおばあさんに、どこまで行くのと尋ねられた。")
  JpnArray3.append("公共の交通機関では不便だから、レンタカーを借りてその街をあちこち見て回るのはどうだろう、とトムは言った。")
  JpnArray3.append("いつ結婚するか、子供を産むか産まないかは、各人の自由な判断によるべきだ。")
  JpnArray3.append("大地震がいつどこで起こるかは予測不可能だ。")
  JpnArray3.append("トムは万事うまくいくと言い張ったが、私は心配で仕方なかった。")
  JpnArray3.append("僕の発言が彼女を傷つけるなんて思いもしなかった。")
  JpnArray3.append("「トム、ごはんですよ」「わかった。すぐ行くよ」")
  JpnArray3.append("成田空港に着いたら電話します。")
  JpnArray3.append("ここから東京ディズニーランドまで電車で行くなら、３回も乗り換えが必要になります。")
  JpnArray3.append("大学を卒業したら海外で仕事を探すことに決めている。")
  JpnArray3.append("このドライヤー、動かないわ。壊れたみたい。")
  JpnArray3.append("アメリカのホームステイで一番うれしかったことは、ホストファミリーの両親が私を自分の娘のように扱ってくれたことです。")
  JpnArray3.append("10代の頃、父の仕事の関係でカナダに3年間住んだことがある。")
  JpnArray3.append("インターネットの普及とともに、ここ数年、パソコンの売り上げが急速に伸びている。")
  JpnArray3.append("トムが水泳の名人だと自慢するのをたびたび聞いたことがあるが、実際に泳いでいるところを見たことがない。")
  JpnArray3.append("コンビニでアルバイトを始めてから１週間にしかならないが、もうすっかり仕事に慣れた。")
  JpnArray3.append("今朝電車に乗ったとき、空いた席が見つからなかった。")
  JpnArray3.append("今はめがねをかけていないので、あの標示になんと書いてあるのかわかりません。")
  JpnArray3.append("私は、故郷に帰れば24時間もしないうちに、自然と地元の方言を話している。")
  JpnArray3.append("人間は5～6歳になる頃には、思ったことを表現できる能力を持つようになる。")
  JpnArray3.append("先日描いてもらった地図のおかげで、迷わずにここまで来ることができました。")
  JpnArray3.append("この夏に2週間の休みをとり、妻とヨーロッパ旅行に行きました。")
  JpnArray3.append("ボブはずいぶんと変わっていたので、この前クラス会で会ったときに彼だとわからなかった。")
  JpnArray3.append("20年ぶりに訪れた故郷はすっかり変わってしまい、昔の面影をとどめていなかった。")
  JpnArray3.append("昨日は数学の予習に追われて4時まで起きていたので、とても眠い。")
  JpnArray3.append("図書館から昨日借りてきた小説を読み終えたので、今はすることがない。")
  JpnArray3.append("この薬を飲んで寝ていれば、たぶん2～3日で良くなっていたのに。")
  JpnArray3.append("先生は、このまま出発すると途中で雷雨に見舞われる危険があるので、しばらくここで待った方がいいと言っています。")
  JpnArray3.append("不老不死は人間の夢である。しかし、もしこれが実現したら地球は人であふれてしまう。")
  JpnArray3.append("アンはうれしそうな顔をしているね。何かいいことがあったに違いない。")
  JpnArray3.append("ヨーロッパの古都に行ったことのある人ならば、町並みの美しさに感動したに違いない。")
  JpnArray3.append("もし石油や石炭などの化石燃料がなかったら、20世紀の歴史はまったく異なったものになっていたに違いない。")
  JpnArray3.append("図書館に来る学生の中には、まるで喫茶店にいるかのように振る舞う者がいる。")
  JpnArray3.append("子供の頃、もう少し家が広ければと思ったものでした。")
  JpnArray3.append("洪水や地震などの被災者を手助けするボランティアとして活動したい。")
  JpnArray3.append("トムは素晴らしいドラムを持っていますが、誰にも使わせません。")
  JpnArray3.append("最初トムは冗談を言っていると思ったが、後で本気だと分かった。")
  JpnArray3.append("この前の日曜日、生まれて初めてイタリア料理に挑戦してみましたが、とってもおいしいものができました。")
  JpnArray3.append("夏は暑くて何をする気にもなれないから嫌いだという人がいます。しかし、海で泳ぐことができるので、私はその夏の暑さが好きです。")
  JpnArray3.append("ジェームズが8年前日本に来たのは、お寺めぐりがしたかっただけでなく、日本人の彼女がいたからだ。")
  JpnArray3.append("私はヒトクローンに反対します。なぜなら独裁者が自らの複製を作り出すことになるかもしれないからです。")
  JpnArray3.append("グラフを見ると、日本における出生率は1985年以降減少している。理由の1つは子育てにお金がかかるからだ。")
  JpnArray3.append("私はアンに遅刻したことを謝ったが、許してくれなかった。")
  JpnArray3.append("数学の授業中に携帯電話が鳴り出して先生にひどく叱られた。電源を切っておかなかったことをとても後悔した。")
  JpnArray3.append("毎日、家事がとても忙しく、映画を観に行く暇がない。")
  JpnArray3.append("この木の机は重いので私1人では2階まで運べない。")
  JpnArray3.append("ヨーロッパ旅行中、どこの国に行っても多くの日本人旅行者に出会うのでうんざりしました。")
  JpnArray3.append("私がプレゼントしたイヤリングをして母が会社に行くのを見て、とてもうれしかった。")
  JpnArray3.append("学校は勉強だけを教えているところだと思うのは、学校の役割を理解していない証拠です。")
  JpnArray3.append("たいていの日本人は、大部分の時間を生きるために働いて過ごす。")
  JpnArray3.append("日本人は、他人を傷つけないように自分の気持ちはできるだけ間接的に表現するのが普通だ。")
  JpnArray3.append("大学の優劣は、図書館の質や規模だけではなく、教師と学生の能力に左右される。")
  JpnArray3.append("大気中のCO2の増加は、地球温暖化と密接な関連がある。")
  JpnArray3.append("現代文明が進めば進むほど、夜型の生活を強いられて睡眠不足になる。")
  JpnArray3.append("医師と教師が似ているところは、どちらも物ではなく人を扱うところである。")
  JpnArray3.append("プロ野球はテレビで見るより球場で見た方が100倍面白い。")
  JpnArray3.append("このバイクは、イギリスでは日本のおよそ２倍の値段です。")
  JpnArray3.append("本を読む量が減ったからといって、今の若者の知的欲求が少なくなったということにはならない。")
  JpnArray3.append("率直に言って、私が昨日受けた入学試験は思っていたよりもはるかに難しかった。")
  JpnArray3.append("パソコンを持っている人は多いが、十分に活用する方法を知っている人は極めて少ない。")
  JpnArray3.append("物価が高すぎると不平を言う主婦が多い。")
  JpnArray3.append("世界には食料が有り余っている国もあれば、何万人もの子供が餓死している国もある。")
  JpnArray3.append("寝る前に必ずエアコンを消しなさい。さもないと風邪をひくかもしれないよ。")
  JpnArray3.append("風邪は万病の元といいます。風邪をひかないように注意しなさい。")
  JpnArray3.append("インターネットでは、世界中の人々と年齢や性別や国籍の違いを超えて意見の交換ができる。")
  JpnArray3.append("いくら運動しても、カロリー計算をしていないと減量は無理だよ。")
  JpnArray3.append("意味を知っているつもりの単語でも、辞書で引いてみると新たな発見があるものだ。")
  JpnArray3.append("日本人観光客の中には、非常識にも多額の現金をズボンの後ろのポケットに入れて持ち歩くものがいる。")
  JpnArray3.append("健康を維持する秘訣は、バランスのとれた食事をし定期的に運動することです。")
  JpnArray3.append("発展途上国でしばらく暮らしてみることは、日本を違った角度から見直すよい機会になる。")
  JpnArray3.append("外国に行って初めて、日本の大都市のネオンの多さに気づく。")
  JpnArray3.append("英語を話せさえすれば国際人になれると勘違いしている日本人が多いのは残念だ。")
  JpnArray3.append("意味が通じる限り、相手の英語の発音のよしあしを気にしないアメリカ人が多いのは驚きです。")
  JpnArray3.append("環境を守るためにできることといったら、ゴミを減らして、できるだけ環境にやさしい製品を使うことぐらいだ。")
  JpnArray3.append("日本の若者の10人のうち7人は、まったく無宗教だと言われる。")
  JpnArray3.append("あいさつの仕方は国によりさまざまだが、日本では、握手よりお辞儀のほうがふつうだ。")
  JpnArray3.append("浜松は、美しい景色と海産物で有名な浜名湖の東に位置しています。")
  JpnArray3.append("年配の女性の中には、１人で何もすることができず妻にしがみついて離れない夫を軽蔑する人も少なくない。")
  JpnArray3.append("その映画館までは徒歩でおよそ20分ですが、地下鉄なら5分で行くことができます。")
  JpnArray3.append("この自転車を修理してもらうのに１万円かかりました。")
  JpnArray3.append("うちは４人家族で、家はこのマンションの５階にあります。")
  JpnArray3.append("若者が活字なら何でも鵜呑みにしてしまうという傾向は、今に始まったことではない。")
  JpnArray3.append("パリに留学していたころ、ある有名な画家に高級レストランでご馳走してもらった経験がある。")
  JpnArray3.append("多くのものを犠牲にして、トムはついに宇宙飛行士になるという夢を実現した。")
  JpnArray3.append("都会の生活でたまったストレスや疲れをとるには、自然の中でのんびりするのが一番です。")
  JpnArray3.append("日本では、女性は出産・育児の後は復職や昇進において不利になる。")
  JpnArray3.append("アメリカでは、自分で運転できる年齢に達するまで、子供はどこに行くにも親に車で送ってもらう。")
  JpnArray3.append("「すみませんが、郵便局までどう行ったらいいですか？」 「２筋目を左です。右にあります。」")
  JpnArray3.append("「今度の先生をどう思う？」 「どこか魅力的なところがあるよね」")
  JpnArray3.append("混雑した電車で、２人分の席を占領して平気な顔をしている人を見ると本当に腹が立つ。")
  JpnArray3.append("人は誰でも生まれながらにして何らかの才能を持っているが、問題はそれを見つけられるかどうかだ。")
  JpnArray3.append("昼ご飯を食べに会社を出たら、高校時代の友達にばったり出会った。")
  JpnArray3.append("この音楽は何度も繰り返して聴く価値がある。君もぜひ聴いてみたらいいよ。")
  JpnArray3.append("歯は健康にとって大切な役割を果たしています。健康でいたければ、毎食後の歯磨きを励行しなければなりません。")
  JpnArray3.append("やる気さえあれば何事においても成功できる、ということを心に留めておきなさい。")

  EngArray3[0] = "It would be dangerous to drink two bottles of whiskey and drive a car."
  EngArray3.append("It is very dangerous to cross a busy street before the light turns green.")
  EngArray3.append("It is really pleasant to take a walk early in the morning, listening to birds sing.")
  EngArray3.append("Most Japanese high school students go to a cram school to prepare for college entrance exams.")
  EngArray3.append("When waiting for the elevator to come or the traffic light to change, most Japanese people become irritated in only thirty seconds.")
  EngArray3.append("An elderly woman sitting next to me on the train asked me where I was going.")
  EngArray3.append("Tom told us that we should rent a car to get around the city because the public transportation was inconvenient.")
  EngArray3.append("Everyone should be free to decide when to get married and whether to have children.")
  EngArray3.append("It is impossible to predict where and when there will be a major earthquake.")
  EngArray3.append("Tom insisted that everything would be all right, but I couldn't help feeling worried.")
  EngArray3.append("It never occurred to me that my remark might hurt her feelings.")
  EngArray3.append("Tom, dinner is ready. OK, Mom. I'm coming.")
  EngArray3.append("I'll call you when I get to Narita Airport.")
  EngArray3.append("If you take the train to Tokyo Disneyland from here, you have to change three times.")
  EngArray3.append("I've decided to look for a job abroad when I graduate from college.")
  EngArray3.append("This dryer doesn't work. Something seems to be wrong with it.")
  EngArray3.append("The best thing about my stay with an American family was that the parents treated me just like their daughter.")
  EngArray3.append("I lived in Canada for three years when I was in my teens because my father was transferred there.")
  EngArray3.append("The Internet is widely used, so sales of personal computers have been rapidly increasing over the last few years.")
  EngArray3.append("I've often heard Tom boast that he is very good at swimming, but I've never actually seen him swim.")
  EngArray3.append("It has been only a week since I began a part-time job at a convenience store, but I'm already used to it.")
  EngArray3.append("When I got on the train this morning, I couldn't find an empty seat.")
  EngArray3.append("I'm not wearing glasses now, so I can't make out what the sign says.")
  EngArray3.append("Less than twenty-four hours after I return to my hometown, without realizing it, I start to talk in the local dialect.")
  EngArray3.append("Humans learn to express what they think by the age of five or six.")
  EngArray3.append("Thanks to the map you drew me the other day, I managed to get here without getting lost.")
  EngArray3.append("Last summer I took two weeks off, and went on a trip to Europe with my wife.")
  EngArray3.append("Bob had changed a lot, so when I saw him at a class reunion, I didn't recognize him.")
  EngArray3.append("When I visited my hometown for the first time in twenty years, I found that it was no longer what it used to be.")
  EngArray3.append("I stayed up till four last night preparing for the math lesson, so I feel very sleepy.")
  EngArray3.append("I've finished reading the novel I borrowed from the library yesterday, so now I have nothing to do.")
  EngArray3.append("If you had taken this medicine and stayed in bed, you would probably have got well in two or three days.")
  EngArray3.append("The teacher says that we should wait here for a while because if we left now, we might get caught in a thunderstorm on the way.")
  EngArray3.append("People wish they could live forever and never become older. However, if this wish came true, there would be too many people on the earth.")
  EngArray3.append("Ann looks happy. Something good must have happened to her.")
  EngArray3.append("If you have been to old European cities, you must have been impressed by the beautiful streets.")
  EngArray3.append("Without fossil fuels such as oil and coal, the history of the 20th century would have been completely different.")
  EngArray3.append("Some students coming to the library act as if they are in a coffee shop.")
  EngArray3.append("When I was a child, I often wished my house were a little larger.")
  EngArray3.append("I'd like to work as a volunteer helping victims of natural disasters, such as floods or earthquakes.")
  EngArray3.append("Tom has nice drums, and he never lets anyone else play them.")
  EngArray3.append("At first I thought Tom was joking, but later I realized he was serious.")
  EngArray3.append("Last Sunday I tried making some Italian food for the first time, and it was delicious.")
  EngArray3.append("Some people say that they don't like summer because it is so hot that they don't feel like doing anything. However, I like the heat of summer because I can swim in the sea.")
  EngArray3.append("James came to Japan eight years ago not only because he wanted to visit temples, but also because he had a Japanese girlfriend.")
  EngArray3.append("I am against human cloning. That is because it could cause duplication of dictators.")
  EngArray3.append("The graph shows that in Japan the birth rate has been decreasing since 1985. This decrease is partly because it costs a lot of money to raise children.")
  EngArray3.append("I apologized to Ann for being late, but she didn't forgive me.")
  EngArray3.append("During the math class, my cell phone began to ring, and the teacher severely scolded me. I regretted that I hadn't turned it off.")
  EngArray3.append("I'm so busy doing the housework every day that I have no time to see a movie.")
  EngArray3.append("This wooden desk is too heavy for me to carry upstairs alone.")
  EngArray3.append("While traveling in Europe, I was disappointed that wherever I went, there were many Japanese tourists.")
  EngArray3.append("I was very happy when I saw my mother going to work wearing the earrings I had bought her.")
  EngArray3.append("If you expect that schools only teach academic subjects, then this proves that you don't understand what schools are for.")
  EngArray3.append("Most Japanese people spend most of their time working to live.")
  EngArray3.append("Japanese people usually express their feelings as indirectly as possible so that they won't offend others.")
  EngArray3.append("Whether a college is good or bad depends not only on how many books its library has and how good they are. It also depends on how intelligent its teachers and students are.")
  EngArray3.append("The increase in the amount of CO2 in the atmosphere is closely connected with global warming.")
  EngArray3.append("The more modern civilization advances, the longer we are forced to stay up at night, and the less sleep we get.")
  EngArray3.append("Doctors and teachers are alike in that both of them deal not with things but with people.")
  EngArray3.append("Professional baseball is far more exciting at a stadium than on TV.")
  EngArray3.append("This motorbike is about twice as expensive in the U.K. as in Japan.")
  EngArray3.append("Just because young people today read less than they used to, it doesn't always follow that they are less eager to learn.")
  EngArray3.append("Frankly speaking, the entrance exams I took yesterday were far more difficult than I had expected.")
  EngArray3.append("A lot of people have personal computers, but very few of them know how to use them effectively.")
  EngArray3.append("A lot of housewives complain that prices are too high.")
  EngArray3.append("In some countries people have too much food, while in others tens of thousands of children are starving.")
  EngArray3.append("Don't forget to turn off the air conditioner before you go to bed, or you'll catch a cold.")
  EngArray3.append("There is a saying that a cold can cause a variety of diseases. Take care not to catch a cold.")
  EngArray3.append("On the Internet, you can exchange thoughts and ideas with people all over the world, regardless of their age, sex, or nationality.")
  EngArray3.append("However much exercise you get, you won't lose weight unless you count your calories.")
  EngArray3.append("Although you believe you know a word, you may learn something new if you look it up in the dictionary.")
  EngArray3.append("Some Japanese tourists lack common sense and carry a lot of cash in their backpockets.")
  EngArray3.append("In order to stay healthy, you should have a balanced diet and get regular exercise.")
  EngArray3.append("If you live in a developing country for a while, you have an opportunity to look at Japan from a different point of view.")
  EngArray3.append("It is not until you go abroad that you realize how many neon lights there are in big Japanese cities.")
  EngArray3.append("It is a pity that many Japanese people mistakenly believe that they have only to speak English to be internationally-minded.")
  EngArray3.append("It is surprising that many Americans don't care how you pronounce English as long as they can understand what you are trying to say.")
  EngArray3.append("The best things you can do to protect nature are to reduce garbage and to use environmentally friendly products.")
  EngArray3.append("It is said that seven out of ten young Japanese people don't believe in religion.")
  EngArray3.append("Ways of greeting vary from country to country. In Japan, bowing is more common than shaking hands.")
  EngArray3.append("Hamamatsu is located east of Lake Hamana, which is famous for its beautiful scenery and delicious fish.")
  EngArray3.append("Quite a few elderly women look down on their husbands, who cannot do anything by themselves and ask too much of them.")
  EngArray3.append("The movie theater is about twenty minutes' walk from here, but it takes only five minutes to get there by subway.")
  EngArray3.append("It cost ten thousand yen to have this bike repaired.")
  EngArray3.append("There are four people in my family. Our apartment is on the fifth floor of this building.")
  EngArray3.append("The tendency for young people to believe everything that is printed is nothing new.")
  EngArray3.append("When I was studying in Paris, a famous painter bought me a meal at a first-class restaurant.")
  EngArray3.append("Tom finally realized his dream of becoming an astronaut, but at the expense of many other things.")
  EngArray3.append("If city life gives you stress and fatigue, it is best to relax in the mountains or on beaches in order to relieve them.")
  EngArray3.append("In Japan, women have difficulty getting promoted or returning to their jobs after giving birth and raising their children.")
  EngArray3.append("In the U.S., parents drive their children everywhere until they are old enough to get a driver's license.")
  EngArray3.append("Excuse me. Could you tell me how to get to the post office? Go straight for two blocks, then turn left. You'll find it on your right.")
  EngArray3.append("What do you think of our new teacher? There is something about her that attracts me.")
  EngArray3.append("People who don't feel guilty about occupying two seats on a crowded train really make me angry.")
  EngArray3.append("Everyone is born with a talent. The question is whether they can find it or not.")
  EngArray3.append("When I left the office for lunch, I ran into an old friend from high school.")
  EngArray3.append("This music is worth listening to over and over again. I recommend it.")
  EngArray3.append("Teeth play an important part in your health. If you want to stay healthy, you should brush your teeth after every meal.")
  EngArray3.append("Bear in mind that if you have enthusiasm, you can succeed in anything.")
  
}
