//
//  EnglishText2.swift
//  Eng_shuffle
//
//  Created by tanakat on 2017/06/17.
//  Copyright © 2017年 tanakat0516. All rights reserved.
//

import Foundation

func setSentence2() {
  
  JpnArray2[0] = "彼らは電車に乗り込んでいる。"
  JpnArray2.append("人々が乗り物から降りている。")
  JpnArray2.append("男性が小さい箱を積み上げている。")
  JpnArray2.append("男性が機器を調節している。")
  JpnArray2.append("道が海まで続いている。")
  JpnArray2.append("木々が円形に並んでいる。")
  JpnArray2.append("彼らはお互い向き合って座っている。")
  JpnArray2.append("男性が曲を演奏している。")
  JpnArray2.append("洋服が店の中に展示されている。")
  JpnArray2.append("人々が床を掃いている。")
  JpnArray2.append("それぞれの机には照明が備え付けられている。")
  JpnArray2.append("人々は手すりにつかまっている。")
  JpnArray2.append("男性たちは棚に商品を補充している。")
  JpnArray2.append("女性は芝刈り機にかがみ込んでいる。")
  JpnArray2.append("歩道橋は通りを見下ろしている。")
  JpnArray2.append("男性が顕微鏡をのぞいている。")
  JpnArray2.append("彼らは書類に取りかかっている。")
  JpnArray2.append("彼女はスーツケースの中身を出している。")
  JpnArray2.append("彼女は用紙に記入している。")
  JpnArray2.append("車が道の脇へ止まろうとしている。")
  JpnArray2.append("彼女は壁にもたれかかっている。")
  JpnArray2.append("彼女はメモを手渡している。")
  JpnArray2.append("建物の建設が進行中である。")
  JpnArray2.append("席はすべてふさがっている。")
  JpnArray2.append("ボール箱がトラックに積まれている。")
  JpnArray2.append("車が両方向別々に走っている。")
  JpnArray2.append("何台かの車が牽引されている。")
  JpnArray2.append("どちらの男性も眼鏡をかけている。")
  JpnArray2.append("男性が車に燃料を入れている。")
  JpnArray2.append("男女2人ともステージで演奏している。")
  JpnArray2.append("人々は相談し合っている。")
  JpnArray2.append("何枚かの皿が流しに積み重ねられている。")
  JpnArray2.append("女性がはかりで野菜の重さを量っている。")
  JpnArray2.append("男性が風景の写真を撮っている。")
  JpnArray2.append("トラックが縁石に止められている。")
  JpnArray2.append("部屋のすべての人が拍手をしている。")
  JpnArray2.append("男性たちが腕組みをして立っている。")
  JpnArray2.append("女性は電話を切っている。")
  JpnArray2.append("女性がベッドを整えている。")
  JpnArray2.append("その家は一部が陰になっている。")
  JpnArray2.append("数人が（船の）デッキに出て座っている。")
  JpnArray2.append("道の両側に通行人がいる。")
  JpnArray2.append("いくつかの建物が水に反射して映っている。")
  JpnArray2.append("公園の真ん中に噴水がある。")
  JpnArray2.append("バイクが放置されている。")
  JpnArray2.append("女性が商品の棚卸表を作っている。")
  JpnArray2.append("シェフが（料理用の）コンロを拭き取っている。")
  JpnArray2.append("客がレジで支払いをしている。")
  JpnArray2.append("部屋で（軽い）飲食物が配られている。")
  JpnArray2.append("列車は運行を中止している。")
  JpnArray2.append("小包が検査されている。")
  JpnArray2.append("男性たちが設計図を見ている。")
  JpnArray2.append("女性たちが廊下で人々とすれ違っている。")
  JpnArray2.append("自転車が通りの両脇に並んでいる。")
  JpnArray2.append("人々が小道に沿ってぶらぶらと歩いている。")
  JpnArray2.append("女性が植物に水をやっている。")
  JpnArray2.append("何人かの人が雑誌をじっと見ている。")
  JpnArray2.append("食料品の代金を支払うためのレーンがいくつかある。")
  JpnArray2.append("女性が商品を並べている。")
  JpnArray2.append("机の上に書類が散らばっている。")
  JpnArray2.append("花が花屋の外で売り出し中になっている。")
  JpnArray2.append("その地域は樹木がよく茂っている。")
  JpnArray2.append("彼女は別の通りへと交通整理をしている。")
  JpnArray2.append("女性が掲示板に掲示物を貼り付けている。")
  JpnArray2.append("イスが折りたたまれている。")
  JpnArray2.append("飛行機の乗組員が階段を下りている。")
  JpnArray2.append("女性は持ち物を片付けている。")
  JpnArray2.append("彼らは川の土手に立っている。")
  JpnArray2.append("男性が赤ん坊を膝に乗せている。")
  JpnArray2.append("女性が庭の草むしりをしている。")
  JpnArray2.append("その建物は一階建てだ。")
  JpnArray2.append("何匹かの犬がひもにつながれている。")
  JpnArray2.append("彼は木から枝を切り落としている。")
  JpnArray2.append("彼女はタマネギを刻んでいる。")
  JpnArray2.append("少年が視力検査をしてもらっている。")
  JpnArray2.append("喫茶店のそばに花壇がある。")
  JpnArray2.append("運転手が小型トラックから降りている。")
  JpnArray2.append("彼女は修了証書をチェックしている。")
  JpnArray2.append("彼らは桟橋に沿って歩いている。")
  JpnArray2.append("絵が額縁に入れられている。")
  JpnArray2.append("ここで口座を開けますか？")
  JpnArray2.append("なぜアンダーソン氏は取締役会に行かなかったのですか？")
  JpnArray2.append("私の書類を一番上の引き出しに入れましたか？")
  JpnArray2.append("渋滞のため電車に間に合いませんでした。")
  JpnArray2.append("いつこの書類を秘書に提出すべきですか？")
  JpnArray2.append("今晩6時以降にお時間はないですよね？")
  JpnArray2.append("このパンフレットをどうすればいいですか？")
  JpnArray2.append("いつ給付金を受ける資格を得られるのですか？")
  JpnArray2.append("あなたがカップにお代わりを入れてくれたのですね？")
  JpnArray2.append("ここで煙草を吸ってもよろしいですか？ はい。")
  JpnArray2.append("面接はいつの予定ですか？")
  JpnArray2.append("明日の天気予報はどうですか？")
  JpnArray2.append("私が書類に目を通すのをお手伝いいただける時間はありませんよね。")
  JpnArray2.append("今年はゲラー氏が販売会議の担当なのですか？")
  JpnArray2.append("請求書は同封しましょうか、それとも後で送りましょうか？")
  JpnArray2.append("出張費はいくらでしたか？")
  JpnArray2.append("ソフトは最新のものになっているのですよね？")
  JpnArray2.append("あなたが取り組んでいるレポートは誰が修正するのですか？")
  JpnArray2.append("いつその会議は行われますか？")
  JpnArray2.append("ロビーで9時15分にお会いするというのはいかがですか？ (9時15分前なら quarter to)")
  JpnArray2.append("いつ新製品は発売されるのですか？")
  JpnArray2.append("1週間の休暇を取るのは誰の番ですか？")
  JpnArray2.append("プロジェクトチームの新しいメンバーは大きな財産ですよね。")
  JpnArray2.append("バスの運賃が少し上がりましたよね。")
  JpnArray2.append("いつ改装は終わるのですか？")
  JpnArray2.append("ロサンゼルス行きの飛行機は予約でいっぱいですか？")
  JpnArray2.append("なぜその服の払い戻しをもらうことができないのですか？")
  JpnArray2.append("今日、処方箋を受け取りに行きましたか？")
  JpnArray2.append("いつ新しい装置は設置されますか？")
  JpnArray2.append("新しい部署を指揮するよう誰が任命されたのですか？")
  JpnArray2.append("ルインスキーさんはわれわれとの仕事に応募してくるつもりですよね。")
  JpnArray2.append("締め切り日までに申込用紙を何とか提出しましたか？")
  JpnArray2.append("今朝の議題は何ですか？")
  JpnArray2.append("今日、営業担当者がくると思いますか？")
  JpnArray2.append("ランプ氏は海外支店に転勤になってしまったんですか？")
  JpnArray2.append("なぜパーティをキャンセルしようと決めたのですか？")
  JpnArray2.append("どれくらいの頻度で市街ツアーバスは来るのですか？")
  JpnArray2.append("会社からタクシーで一緒に行くっていうのはどう？")
  JpnArray2.append("どこで御社の商品パンフレットを手に入れられますか？")
  JpnArray2.append("すでにカッタン女史との約束はできていますか？")
  JpnArray2.append("明日、駅まで車で送っていきましょうか？")
  JpnArray2.append("けさのマネージャーの提案は意味をなしませんでしたよね。")
  JpnArray2.append("この水玉のネクタイはあなたの青いジャケットによく合うはずです。")
  JpnArray2.append("その件については、水曜日までに返事をさせてください。")
  JpnArray2.append("契約の有効期限はいつですか？")
  JpnArray2.append("返却期限を過ぎた本に課せられる延滞料はいくらですか？")
  JpnArray2.append("事務用品の請求書は受け取りましたよね。")
  JpnArray2.append("もう研修会に申し込みましたか？")
  JpnArray2.append("発送をキャンセルしましょうか、それとももう一週間待ちましょうか？")
  JpnArray2.append("事務用品の購入の払い戻しを受けたのですよね？")
  JpnArray2.append("もう提案書を作成しましたか？")
  JpnArray2.append("早朝シフトを誰が引き受けるつもりですか？")
  JpnArray2.append("商品をどのようにお送りすればよろしいでしょうか？")
  JpnArray2.append("タンザニアで最もいいお土産は何だと思いますか？")
  JpnArray2.append("この仕事におけるあなたの抱負は何ですか？")
  JpnArray2.append("なぜ御社はそんなにたくさんのアルバイトを解雇したのですか？")
  JpnArray2.append("この報告書を中国語に翻訳してもらうつもりですか？")
  JpnArray2.append("いつ私の昇進が給料に反映されるのですか？")
  JpnArray2.append("ボールドウィン氏は専務取締役になるのに心配でもあるのでしょうか？")
  JpnArray2.append("マネージャーは来週まで会議を延期することを決めました。")
  JpnArray2.append("その機械部品の交換物はどこで見つけることができますか？")
  JpnArray2.append("このコンピュータ端末の電源の入れ方を教えていただけませんか？")
  JpnArray2.append("タナカ氏がこの建設プロジェクトを許可したのですよね。")
  JpnArray2.append("その年次報告書に関してまだやらなければならないことがありますか？")
  JpnArray2.append("このコピー機には保証書は付いていないのですか？")
  JpnArray2.append("夏物の洋服の値段が値引きされたんですよね。")
  JpnArray2.append("納品業者からの請求書を整理しましたか？")
  JpnArray2.append("部長のところへ行って、新しい合意を却下するよう頼んでみましょうか？")
  JpnArray2.append("倉庫の中にある書類用整理棚を探してくれる？")
  JpnArray2.append("あなたが電話で呼び出したい相手の名前は何ですか？")
  JpnArray2.append("私の昇進の見込みはどうでしょうか？")
  JpnArray2.append("売上高を示す図の準備はできましたか？")
  JpnArray2.append("あなたは転勤の候補者として立候補するのですか？")
  JpnArray2.append("ユン氏は私を大目に見てくれると思いますか？")
  JpnArray2.append("週間報告書のその数字を除外してほしいですか？")
  JpnArray2.append("直属の上司による評価はどうだった？")
  JpnArray2.append("どの請負業者が一番手ごろな入札価格を申し出ているの？")
  JpnArray2.append("その新しい仕事を引き受けるのは誰に割り当てられそうですか？")
  JpnArray2.append("私どものタイにある製造工場を見学なさいますか？")
  JpnArray2.append("何時にお食事になさいますか？")
  JpnArray2.append("朝いちばんで売り上げ予想を机の上に置いておいてください。")
  JpnArray2.append("残念ながら月曜日は都合がつきません。")
  JpnArray2.append("セミナーは金曜日に再調整された。")
  JpnArray2.append("私は数日間休暇を取ることになっている。")
  JpnArray2.append("今、下のATMでお金を引き出せると思いますか？")
  JpnArray2.append("明日の夜の予約を確認したいのですが？")
  JpnArray2.append("新しいオフィスは私が思ったより広い。")
  JpnArray2.append("われわれは二日間予定より遅れている。")
  JpnArray2.append("申し訳ございませんが、小さいサイズのシャツは在庫切れです。")
  JpnArray2.append("宣伝についてのいいアイデアを思いついたら、知らせてください。")
  JpnArray2.append("イトウ氏のプレゼンテーションは、まだあと20分は始まりません。")
  JpnArray2.append("来年、本社はフロリダに移転するらしいですね。")
  JpnArray2.append("なぜナカノコーポレーションからの仕事のオファーを断ったのですか？")
  JpnArray2.append("頼まれていた事務用品の注文をしました。")
  JpnArray2.append("ガソリンがなくなってきたから、ガソリンスタンドに寄りましょう。")
  JpnArray2.append("飛行機が遅れたので、会議に間に合いませんでした。")
  JpnArray2.append("電話を転送している間、そのままお待ちください。")
  JpnArray2.append("履歴書を見せてくれませんか？")
  JpnArray2.append("休暇を取る前に、四半期報告書を書き終えなければなりません。")
  JpnArray2.append("その美術雑誌の予約購読をしているのですか？")
  JpnArray2.append("空港まで誰かにイトー氏を迎えに行かせないといけません。")
  JpnArray2.append("上司とはあまり(関係が)うまくいきません。")
  JpnArray2.append("ムーア医師が来週火曜日の午後に空きがあるかどうかは分かりません。")
  JpnArray2.append("仕事量が多すぎて、明日までにレポートを仕上げられそうにありません。")
  JpnArray2.append("部品納入業者が再来週にストをするでしょう。")
  JpnArray2.append("ひょっとして来週私の代わりを引き受けてくれる？")
  JpnArray2.append("あなたにサムソン社からのメールを転送しました。")
  JpnArray2.append("トムはずっと会議中です。時間通りには間に合いません。")
  JpnArray2.append("なぜコンサートが中止になったのか分かったかい？")
  JpnArray2.append("ロンドン行きの飛行機が予約でいっぱいなら電話をください。")
  JpnArray2.append("すでに補助金の申請用紙に記入しましたか？")
  JpnArray2.append("クレジットカードで大丈夫です。")
  JpnArray2.append("もうすぐに一緒に働けることを楽しみにしています。")
  JpnArray2.append("明日、朝8時半に予定を組み込むことができますが。")
  JpnArray2.append("この掃除機を作動させられない。")
  JpnArray2.append("管理部主任の職に集まった応募書類を選考しているところです。")
  JpnArray2.append("ウィットマンさんはしばらくの間仕事を休んでいますよね。")
  JpnArray2.append("そのプロジェクトを実行するのにどれだけの時間が割り当てられているのですか？")
  JpnArray2.append("レシートを貼り付けた請求用紙をマネージャーに提出してください。")
  JpnArray2.append("何らかの身分証明書か大手のクレジットカードを見せてもらえますか？")
  JpnArray2.append("私たちは今週中に解決法を打ち出さなければなりません。")
  JpnArray2.append("同僚に贈る誕生日の贈り物を探しています。")
  JpnArray2.append("仕事量が適切に割り当てられているとは思いません。")
  JpnArray2.append("今の状況は長くは続かないので、計画を促進するべきです。")
  JpnArray2.append("ジェイソン氏はひどい風邪をひきました。")
  JpnArray2.append("この地域にはなじみがないので、曲がるところを間違えました。")
  JpnArray2.append("仕様書は土曜日の朝が締め切りでしたよね。")
  JpnArray2.append("すぐに一時的な代わりの人を見つけなくてはなりません。")
  JpnArray2.append("売り上げが回復したら、生産高を減らすべきだと思います。")
  JpnArray2.append("委員会は木曜日の午後に予定されています。")
  JpnArray2.append("予算が厳しいので、節約しなければなりません。")
  JpnArray2.append("社用箋が不足しています。")
  JpnArray2.append("職探しはうまくいっていますか？")
  JpnArray2.append("昨日の年次集会の参加者はどのくらいいましたか？")
  JpnArray2.append("家庭用電気製品売り場はどこですか？")
  JpnArray2.append("あなたのアドバイスに感謝します。確かにうまくいきました。")
  JpnArray2.append("この2階建ての家はすぐに改築されるでしょう。")
  JpnArray2.append("工場でのストライキのため、作業が止まってしまいました。")
  JpnArray2.append("補償申請用紙をどこで受け取ればいいのか教えてください。")
  JpnArray2.append("マルコスさんはすべての数字をやり直すよう私にいってきました。")
  JpnArray2.append("新聞でその劇のすばらしい評論を読みました。")
  JpnArray2.append("予算には十分なお金が残っていません。")
  JpnArray2.append("外貨を受け付けてくれますか？")
  JpnArray2.append("年1回の健康診断を受けるように言われました。")
  JpnArray2.append("（箱の）中身の価値はどれくらいですか？")
  JpnArray2.append("プレゼン用の図に取りかかっているところです。")
  JpnArray2.append("誰に休暇の申請を話せばいいのですか？")
  JpnArray2.append("「新しい企画はどうですか？」「まだわずか半分しか終わっていません」")
  JpnArray2.append("新聞で宣伝されていたそちらの商品を拝見しました。")
  JpnArray2.append("リー氏は優良株を150株購入しました。")
  JpnArray2.append("ニューマン氏はその仕事には経験がありすぎると思います。")
  JpnArray2.append("誰が現場監督の仕事を引き継ぐのですか？")
  JpnArray2.append("どうやって商品の注目度を上げたらいいでしょうか？")
  JpnArray2.append("その造園会社が私たちに保管場所を貸し出すことを申し出てくれて運がいい。")
  JpnArray2.append("人を雇うのではなく、広告予算を増やすべきです。")
  JpnArray2.append("もう発信郵便物は分別されていますか？")
  JpnArray2.append("通常の郵便で、この包みをボストンに送ってもらいたいのですが。")
  JpnArray2.append("私のオフィスの暖房システムは何らかの機能不良が見られます。")
  JpnArray2.append("われわれのいるビルは明日、火災訓練を行いますのでお忘れなく。")
  JpnArray2.append("人事部のサムに電話をして、採用について何ができるか確かめてみるよ。")
  JpnArray2.append("今日の基調講演者のスピルバーグ氏をご紹介します。")
  JpnArray2.append("全従業員を代表して、新会長に祝杯をあげたいと思います。")
  JpnArray2.append("イベントのさらに詳しい情報は私たちのホームページに掲載されています。")
  JpnArray2.append("ホームページを念入りにデザインすることは、長期的に必ず利益をもたらします。")
  JpnArray2.append("パソコン販売の最近の急増で、顧客からの需要も増えました。")
  JpnArray2.append("エリソン氏とお仕事できることを大変名誉に思います。")
  JpnArray2.append("お得な月々の分割払いに加え、年会費は無料です。")
  JpnArray2.append("今後の最新の交通情報のために、このまま（このラジオ局を）お聞きください。")
  JpnArray2.append("これらの方針に従うなら、いままで以上の給料を得られることでしょう。")
  JpnArray2.append("キングダム大学のハリントン博士を一緒にお迎えいたしましょう。")
  JpnArray2.append("TFA106便にご搭乗のお客様は、17Bゲートまでお進みください。")
  JpnArray2.append("収益は小児病院に寄付されます。")
  JpnArray2.append("これにより生じる不便に対しておわびし、ご辛抱に感謝いたします。")
  JpnArray2.append("ツアー開始前に、簡単に今日の活動の予定を見直しておきたいと思います。")
  JpnArray2.append("食堂は限られた人数しか収容できないことをお含みおきください。")
  JpnArray2.append("機内でのお買い物商品リストについては、無料の航空会社専用雑誌をご覧ください。")
  JpnArray2.append("皆様、ワグナー氏に大きな拍手をお願いします。")
  JpnArray2.append("残念ながら078便は悪天候により遅れています。")
  JpnArray2.append("MPM社はこの5月に受賞パーティに引き続き店内娯楽行事を行い、創業30周年記念をする予定です。")
  JpnArray2.append("ご質問がおありでしたら遠慮なく私どもにご連絡ください。")
  JpnArray2.append("ご予約を完了するために、150ドルの頭金がすぐに必要です。")
  JpnArray2.append("乗務員が参りました折に、ご注文とお支払いを準備しておいてください。")
  JpnArray2.append("私と一緒に働いてくれたエンジニアたちに感謝したいと思います。")
  JpnArray2.append("皆さんは第一線の心理学者であるフォックス女史の豊富な経験から得ることがあるはずです。")
  JpnArray2.append("お支払いはクレジットカードのみとさせていただきますことをご了承ください。")
  JpnArray2.append("旅行の手配がすべて確認されましたのでお知らせいたします。")
  JpnArray2.append("デル氏の何年にもわたる食品業界への貢献は、目を見張るものがあります。")
  JpnArray2.append("新しい市の条例に従って、お体の不自由な方用に施設の改善をする予定です。")
  JpnArray2.append("午後の会議は3階で行われ、昼食はオハナ部屋で支給されます。")
  JpnArray2.append("繊細な（動植物の）生息地保護のため、滝のそばの花を摘み取るのはご遠慮ください。")
  JpnArray2.append("このアナウンスは、アジア料理に興味がある方に向けています。")
  JpnArray2.append("フォックス氏との面会の件についてお電話差し上げました。")
  JpnArray2.append("こちらはD&S不動産です。")
  JpnArray2.append("通常の営業時間であれば就職活動セミナーに登録することができます。")
  JpnArray2.append("市民センターで来る日曜日に開催される家族のための催しをお見逃しなく。")
  JpnArray2.append("緊急事態の際には、避難手順に従わなければなりません。")
  JpnArray2.append("コピーする時はカバーを閉じるのを忘れないように。")
  JpnArray2.append("本日午後、空調システムのテストを行う予定です。")
  JpnArray2.append("弊社はまもなく、すべての関連場所でリサイクル計画を開始します。")
  JpnArray2.append("予期せぬ市外での会議のため、アポイントを取り直したいのです。")
  JpnArray2.append("改築のため、おもちゃ店は今月末まで閉まっています。")
  JpnArray2.append("乗客は航空会社カウンターまで進み、近くのホテルでの一泊の宿泊がついている無料クーポン券をもらってください。")
  JpnArray2.append("気象庁は地元ラジオ局に暴風雨警報を出すよう指示した。")
  JpnArray2.append("お年寄りと障害者のための優先席があります。")
  JpnArray2.append("携帯用電気器具は離陸に先立ち必ずお切りください。")
  JpnArray2.append("新しい暖房装置の取り付けが今週末に始まる予定です。")
  JpnArray2.append("400ドル以上の価値のある商品を購入されましたら、無料で配送いたします。")
  JpnArray2.append("翌日まで公聴会は延期されました。")
  JpnArray2.append("今日のゲストはエネルギー効率のいい照明器具の専門家であるデッドルーカス氏です。")
  JpnArray2.append("害虫コントロールの心配がいらないようそのための多数の選択肢をご提供いたします。")
  JpnArray2.append("来週付けで、すべての従業員は研究室に入室する際、安全眼鏡を装着しなければなりません。")
  JpnArray2.append("その物件はすでにコンピュータネットワークにつながっています。")
  JpnArray2.append("多くの航空会社が最近、払い戻し不可のチケットに関する方針を変更しました。")
  JpnArray2.append("寄付が前年より10パーセント増加しましたが、これはおそらく環境保護に対する一般の関心の高まりによるものです。")
  JpnArray2.append("市内にかぎり無料配送を行いますことをよろこんでご報告いたします。")
  JpnArray2.append("本のサイン会やクラシックの演奏といった催し物が、展示会を補足するために催されます。")
  JpnArray2.append("海外事業の売り上げが急激に伸びたので、次の四半期は全体的な利益増加が見込まれます。")
  JpnArray2.append("火事のときは、安全ゴーグルをつけて、正しく消化器を使ってください。")
  JpnArray2.append("私どもの経験豊富で免許のある会計士がご質問にお答えします。")
  JpnArray2.append("テイラーさんがあなたとご家族が苦労せず落ち着くことができるようお世話します。")
  JpnArray2.append("機械の定期的な保守点検を強くお勧めします。")
  JpnArray2.append("すべての従業員が工場ではヘルメット着用を義務づけられています。")
  JpnArray2.append("ガソリンの値段は地域により異なっている。")
  JpnArray2.append("天気予報に反して、晴れ上がり暑くなったため、セーターを着てきたことを後悔した。")
  JpnArray2.append("そのシステムの運用マニュアルは今後の参考のためにオフィスに保管されている。")
  JpnArray2.append("競争の激しい市場の多くの小企業は、結局倒産に終わる。")
  JpnArray2.append("3年連続で利益が減少したことが原因で、CEOは辞任を申し出た。")
  JpnArray2.append("依頼人は、契約書に署名する前に但し書きを読むようにと忠告された。")
  JpnArray2.append("顧客は購入日から10日以内であれば返品をする資格があります。")
  JpnArray2.append("最近の売り上げの急増は、市場での当社の製品に対する需要が伸びているためだ。")
  JpnArray2.append("製品の開発が終了したらすぐに、市場に宣伝する予定だ。")
  JpnArray2.append("相次ぐ事故のために、会社は安全規則を施行した。")
  JpnArray2.append("サイテック・インフォ社は、質が高く洗練された商品の提供に全力を注いでいる。")
  JpnArray2.append("翌日配送は追加料金の対象になる。")
  JpnArray2.append("新しい条例は4月に施行される予定だ。")
  JpnArray2.append("その商品は銀行振り込みで購入することができる。")
  JpnArray2.append("ネットでの申し込みしか受け付けないことにご留意ください。")
  JpnArray2.append("その主力製品は会社の収入の40%を占めている。")
  JpnArray2.append("コンサート中の貴重品の紛失については皆様自身の責任になります。")
  JpnArray2.append("アムステルダムホテルは大きなツアーグループを収容できる。")
  JpnArray2.append("新しい設備のおかげで、生産が著しく増加するだろう。")
  JpnArray2.append("ウッド氏はその仕事をするのに十分な資格がある。")
  JpnArray2.append("私どもの商品にもし万が一ご質問がありましたら、ご連絡ください。")
  JpnArray2.append("締め切りに間に合わせることができないと思おうなら、上司に相談しなさい。")
  JpnArray2.append("営業部員の話し方を考慮に入れると、大幅な売り上げ減少が見込まれる。")
  JpnArray2.append("私どもの指導ビデオは、専門家による実演で、日々の決まった運動を紹介しています。")
  JpnArray2.append("5月に行われる本会議の開催地はどこですか？")
  JpnArray2.append("マービンモーターズ社は9月30日付で業務を停止します。")
  JpnArray2.append("害を及ぼすすべての物質を子どもの手の届くところや見えるところにおかないでください。")
  JpnArray2.append("会議の中で、運営経費を削減する一時的な代替案が提示された。")
  JpnArray2.append("インドへの転勤が予告なしに決定したので、ホム氏はとても当惑している。")
  JpnArray2.append("宣伝用のビラとポスターはこの企画には不可欠だ。")
  JpnArray2.append("保険料が値上げされるだろうと会社から発表があった。")
  JpnArray2.append("ソフト開発以外に、弊社は配送の責任も負います。")
  JpnArray2.append("便宜のため、自動販売機をラウンジに設置いたしました。")
  JpnArray2.append("給料と給付金の削減は従業員の仕事の質に影響を及ぼすだろう。")
  JpnArray2.append("顧客サービス係はマニュアルにある規則に従うよう要求されている。")
  JpnArray2.append("経済の見通しがよくないので、これ以上の投資はなされないだろう。")
  JpnArray2.append("あなた様用の設計仕様書を同封いたしましたので、どうぞご覧ください。")
  JpnArray2.append("針治療など補助療法のご利用をお考えになることをおすすめします。")
  JpnArray2.append("その会社は生産ラインを削減することを決定した。")
  JpnArray2.append("多くの経済評論家は、近い将来のコンピュータ市場の急速な成長は期待できないと主張している。")
  JpnArray2.append("これ以上進む前に、私たちの製品が実用的で売り物になるのかどうかの調査を行う必要がある。")
  JpnArray2.append("国会は昨日、生年月日から住所にいたるまで、個人情報を保護する法律を制定した。")
  JpnArray2.append("取締役会はマーケットリサーチに着手することに全会一致で合意した。")
  JpnArray2.append("私どもの会社には、副社長に直属するポジションがいくつかある。")
  JpnArray2.append("今度の展示会では最新のインターネット・テクノロジーが披露される。")
  JpnArray2.append("経済が原因で失業率が増え続けている。")
  JpnArray2.append("会社は商品開発に十分な予算を割り当てた。")
  JpnArray2.append("先月宣伝キャンペーンを始めたにもかかわらず、まだ売り上げの伸びは見えない。")
  JpnArray2.append("インフォ・セカンド社は上昇し続ける社員の離職率を懸念している。")
  JpnArray2.append("放置されていたり、不審に見える荷物は開けて調べられます。")
  JpnArray2.append("平均して、その会社は過去4年間、20%ずつ売り上げを伸ばしている。")
  JpnArray2.append("そのホテルは非公式のビジネス行事に使われることになっている。")
  JpnArray2.append("その情報は直接会社からではなく外部から手に入れることができる。")
  JpnArray2.append("キング氏は昇進したとき、すぐに昇給を要求した。")
  JpnArray2.append("広告に割り当てられる予算はかなり制限がある。")
  JpnArray2.append("タッカー女史の銀行家としての知識が、交渉が進むにつれ当てにされるでしょう。")
  JpnArray2.append("警察はスポーツ賭博による非合法的賭け事でのもうけを没収するつもりだ。")
  JpnArray2.append("従業員ボランティアが一時的な人員不足を緩和することができる。")
  JpnArray2.append("満席のファンションショーで、その服飾デザイナーのキャリアは絶頂に達した。")
  JpnArray2.append("道路閉鎖のため、迂回標識がその場所の周辺に設置されることになっている。")
  JpnArray2.append("その取引記録を注意して扱わなければならい。")
  JpnArray2.append("その収穫機はすべてのパーツと人件費を含み2年間の保証期間がある。")
  JpnArray2.append("子どもの日を祝って、月曜日は保育園が閉園になる。")
  JpnArray2.append("ご自分の銀行残高をお知りになりたいなら、パスワードを入れて2を押してください。")
  JpnArray2.append("私の同僚がご遺族の方々に哀悼の意を表したがっています。")
  JpnArray2.append("模範的な記録を維持できている従業員に賞が授与される。")
  JpnArray2.append("宴会では従業員はきちんとしたビジネス用の服装をするよういわれている。")
  JpnArray2.append("時間の制約上、スター氏は結局年次報告書を仕上げることをしなかった。")
  JpnArray2.append("主任エンジニアのバーカー女史はコンピュータフィルタに無制限アクセスできる。")
  JpnArray2.append("フロリダ州は州民を熱帯性暴風雨から守るための手段を講じている。")
  JpnArray2.append("会社の倫理規範のいかなる違反も、それ相応の処罰を受けるこことする。")
  JpnArray2.append("経費引換券は、記入して、3通にコピーしておかなければなりません。")
  JpnArray2.append("私どものサービスに関して、皆さまからのコメントを心より感謝して拝聴いたします。")
  JpnArray2.append("ウエイド氏はその計画に関して反対の見解を表明するよう依頼されるだろう。")
  JpnArray2.append("リー女史がその式典で国際的に著名な高官を接待する。")
  JpnArray2.append("私どもの海外留学プログラムは有益な国際親善を強化するの役立っています。")
  JpnArray2.append("配達品をよく調べてみたところ、欠陥品を何点か発見しました。")
  JpnArray2.append("実施チームのメンバーはマーケティングコミュニケーション局により承認される。")
  JpnArray2.append("競合社のマーケティングキャンペーンが私たちのものより優れていることは明らかだ。")
  JpnArray2.append("ひどい交通事故が交差点の真ん中で起きた。")
  JpnArray2.append("プレゼンテーションの前に、もう一度徹底して書類の間違いをチェックしてください。")
  JpnArray2.append("出る前にすべての電気が消されていることを確認してください。")
  JpnArray2.append("このソフトウェアはインターネットから音楽をダウンロードすることを可能にする。")
  JpnArray2.append("キャンセルは書面にて会合の7日前までにお知らせください。")
  JpnArray2.append("もし商品を展示したいのなら、いま登録して、私どもの特別レートをご利用ください。")
  JpnArray2.append("トラックのキャブレターは値段の高さにかかわらず、修理しなければならない。")
  JpnArray2.append("残念ながら、お問い合わせの本はすでに絶版になっております。")
  JpnArray2.append("オフィスの備品を大量に購入したい人は来週までに申込書を提出しなければならない。")
  JpnArray2.append("個人または商業目的で、許可なく構内で写真を撮ることは厳しく禁止されています。")
  JpnArray2.append("ホテルの宿泊客は部屋の中で設備を取り外すことはつつしまなくてはいけない。")
  JpnArray2.append("コンピュータ作動による組み立てラインの開発は過去10年の重要な革新のひとつである。")
  JpnArray2.append("その営業部長は売り上げの急増に大いに貢献した。")
  JpnArray2.append("絵画収集家は、しばしば芸術家に歩合制で作品の創出を依頼する。")
  JpnArray2.append("ある報告によると、国の半数以上の学校は換気が悪い。")
  JpnArray2.append("評議員会からの報告書はHTML形式で利用できます。")
  JpnArray2.append("IT産業の優れた職業見通しから、彼女はNSAコパック社に就職した。")
  JpnArray2.append("そのとき転職することは、単にウォング氏の利益にならなかった。")
  JpnArray2.append("農務大臣はその分野を発展させるために使える技術を利用するよう農場主たちに奨励している。")
  JpnArray2.append("登録用紙にご記入のうえ、ウエストランドダンススクール宛の小切手と一緒にどうかお戻しください。")
  JpnArray2.append("ある新しい報告では、小規模校のほうが大規模校より学生の達成度において優れているという証拠がある。")
  JpnArray2.append("その新しいデータベースは、高い期待に応えることができなかった。")
  JpnArray2.append("就業規則によれば、すべての従業員は解雇について少なくとも1ヵ月前には通告されなければならない。")
  JpnArray2.append("選挙の年の間は、有権者は毎日テレビのニュースショーを見る。")
  JpnArray2.append("理想的な候補者はデータ管理に熟達していなければならない。")
  JpnArray2.append("自動化とより質のいい肥料が農場労働力の減少を埋め合わせてくれるだろう。")
  JpnArray2.append("その基金の目的は、音楽演奏を通じ何百万という人々に喜びをもたらす才能ある人に敬意を表すことです。")
  JpnArray2.append("売り上げ報告書の訂正は今月の終わりにか、来月の初めに行われる予定になっている。")
  JpnArray2.append("電子メールに何日も返答しないままよりは、タイミングよく返信してください。")
  
  EngArray2[0] = "They are boarding the train."
  EngArray2.append("People are leaving the vehicle.")
  EngArray2.append("The man is piling up some small boxes.")
  EngArray2.append("The man is adjusting the machine.")
  EngArray2.append("The path leads to the sea.")
  EngArray2.append("The trees are arranged in a circle.")
  EngArray2.append("They are sitting across from each other.")
  EngArray2.append("The man is playing a musical piece.")
  EngArray2.append("Some clothes are displayed in the store.")
  EngArray2.append("People are sweeping the floor.")
  EngArray2.append("Each desk is equipped with a light.")
  EngArray2.append("People are holding the railings.")
  EngArray2.append("The men are stocking shelves.")
  EngArray2.append("The woman is bending over the lawnmower.")
  EngArray2.append("The overpass overlooks the street.")
  EngArray2.append("The man is looking through the microscope.")
  EngArray2.append("They are working on a document.")
  EngArray2.append("She is unpacking her suitcase.")
  EngArray2.append("She is filling out the form.")
  EngArray2.append("The car is pulling over to the side of the road.")
  EngArray2.append("She is leaning against the wall.")
  EngArray2.append("She is handing out some notes.")
  EngArray2.append("Construction of the building is in progress.")
  EngArray2.append("All of the seats are occupied.")
  EngArray2.append("Cardboard boxes are being loaded onto the truck.")
  EngArray2.append("Traffic is moving in both directions.")
  EngArray2.append("A couple of cars are being towed away.")
  EngArray2.append("Both men are wearing glasses.")
  EngArray2.append("The man is putting fuel in the vehicle.")
  EngArray2.append("Both man and woman are performing onstage.")
  EngArray2.append("The people are consulting with each other.")
  EngArray2.append("Several plates are being stacked in the sink.")
  EngArray2.append("The woman is weighing some vegetables on a scale.")
  EngArray2.append("The man is photographing the landscape.")
  EngArray2.append("The truck is being parked at the curb.")
  EngArray2.append("All of the people in the room are clapping their hands.")
  EngArray2.append("The men are standing with their arms crossed.")
  EngArray2.append("The woman is hanging up the telephone.")
  EngArray2.append("The woman is making the bed.")
  EngArray2.append("The house is partially shaded.")
  EngArray2.append("Some people are sitting out on the deck.")
  EngArray2.append("There are pedestrians on both sides of the road.")
  EngArray2.append("Some buildings are reflected in the water.")
  EngArray2.append("There is a fountain in the center of the park.")
  EngArray2.append("The motorbike is unattended.")
  EngArray2.append("The woman is taking an inventory of articles.")
  EngArray2.append("The chef is wiping off the stove.")
  EngArray2.append("The customer is paying the cashier.")
  EngArray2.append("Refreshments are being provided in the room.")
  EngArray2.append("The train is out of service.")
  EngArray2.append("A parcel is being inspected.")
  EngArray2.append("The men are looking at blueprints.")
  EngArray2.append("Women are passing people in the hallway.")
  EngArray2.append("Bicycles are lined up on both sides of street.")
  EngArray2.append("People are strolling along the path.")
  EngArray2.append("The woman is watering the plants.")
  EngArray2.append("Some people are gazing down at the magazine.")
  EngArray2.append("There are several lanes to pay for the groceries.")
  EngArray2.append("The woman is arranging the merchandise.")
  EngArray2.append("Papers are scattered on the desk.")
  EngArray2.append("The flowers are for sale outside the florist.")
  EngArray2.append("The area is heavily wooded.")
  EngArray2.append("She is directing the traffic to another street.")
  EngArray2.append("The woman is putting a notice on the bulletin board.")
  EngArray2.append("The chairs have been folded up.")
  EngArray2.append("The flight crew is descending the stairs.")
  EngArray2.append("The woman is putting away her belongings.")
  EngArray2.append("They are standing on the river bank.")
  EngArray2.append("The man is holding the baby on his lap.")
  EngArray2.append("The woman is weeding the garden.")
  EngArray2.append("The building has only one story.")
  EngArray2.append("The dogs are on leashes.")
  EngArray2.append("He is cutting the branch off the tree.")
  EngArray2.append("She is chopping up the onions.")
  EngArray2.append("The boy is having his eyes examined.")
  EngArray2.append("There is a bed of flowers by the café.")
  EngArray2.append("The driver is stepping out of the van.")
  EngArray2.append("She is checking the certificates.")
  EngArray2.append("They are walking along the pier.")
  EngArray2.append("A painting is being framed.")
  EngArray2.append("Can I open an account here?")
  EngArray2.append("Why didn't Mr. Anderson go to the board meeting?")
  EngArray2.append("Did you put my document in the top drawer?")
  EngArray2.append("I couldn't make it to the train because of heavy traffic.")
  EngArray2.append("When should I hand in this document to the secretary?")
  EngArray2.append("You won't be available after six tonight, will you?")
  EngArray2.append("What are we supposed to do with these brochures?")
  EngArray2.append("When will you be eligible for benefits?")
  EngArray2.append("You refilled my coffee cup, didn't you?")
  EngArray2.append("Would you mind my smoking here? No.")
  EngArray2.append("When is the interview scheduled for?")
  EngArray2.append("What's the weather forecast for tomorrow?")
  EngArray2.append("You don't have any time to help me go over the documents, do you?")
  EngArray2.append("Is Mr. Geller in charge of the sales conference this year?")
  EngArray2.append("Should we enclose the invoice, or will we send it later?")
  EngArray2.append("How much were the travel expenses?")
  EngArray2.append("Our software has been updated, hasn't it?")
  EngArray2.append("Who will revise the report you're working on now?")
  EngArray2.append("When does the conference take place?")
  EngArray2.append("What do you say to meeting at a quarter of nine in the lobby?")
  EngArray2.append("When will the new product be launched?")
  EngArray2.append("Whose turn is it to take a week-long vacation?")
  EngArray2.append("The new member of our project team is a real asset, isn't she?")
  EngArray2.append("The bus fare has gone up a bit, hasn't it?")
  EngArray2.append("When will the renovation be over?")
  EngArray2.append("Are the flights to Los Angeles fully booked?")
  EngArray2.append("Why can't I get a refund on the outfit?")
  EngArray2.append("Did you pick up your prescriptions today?")
  EngArray2.append("When will the new equipment be installed?")
  EngArray2.append("Who has been appointed to direct the new department?")
  EngArray2.append("Ms. Lewinsky is going to apply for a job with us, isn't she?")
  EngArray2.append("Did you get to turn in the application form by the due date?")
  EngArray2.append("What's on the agenda for this morning?")
  EngArray2.append("Do you think the sales representative is coming today?")
  EngArray2.append("Has Mr. Lamp been transferred to the overseas branch?")
  EngArray2.append("What made you decide to call off the party?")
  EngArray2.append("How frequently does the city tour bus come?")
  EngArray2.append("Why don't we share a cab from the office?")
  EngArray2.append("Where can I obtain the brochure of your products?")
  EngArray2.append("Have the arrangements with Ms. Kattan already been made?")
  EngArray2.append("Do you need a ride to the station tomorrow?")
  EngArray2.append("The manager's proposal this morning didn't make sense, did it?")
  EngArray2.append("This polka-dot tie should go well with your blue jacket.")
  EngArray2.append("Let me get back to you on that matter by Wednesday.")
  EngArray2.append("When is the expiration date of the contract?")
  EngArray2.append("What is the fine for overdue books?")
  EngArray2.append("You got the invoice for the office supplies, didn't you?")
  EngArray2.append("Have you signed up for the workshop yet?")
  EngArray2.append("Should we cancel the shipment, or do we wait for another week?")
  EngArray2.append("You got reimbursed for the purchase of the office supplies, didn't you?")
  EngArray2.append("Have you drawn up the proposal yet?")
  EngArray2.append("Who is covering the early morning shift?")
  EngArray2.append("How would you like your items shipped?")
  EngArray2.append("What do you think is the best souvenir of Tanzania?")
  EngArray2.append("What are your aspirations in this job?")
  EngArray2.append("Why did your company lay off so many part-timers?")
  EngArray2.append("Are you going to have this report translated into Chinese?")
  EngArray2.append("When will my raise show up in my paycheck?")
  EngArray2.append("Does Mr. Baldwin have any reservations about becoming a managing director?")
  EngArray2.append("The manager decided to postpone the meeting until next week.")
  EngArray2.append("Where can I find the replacement for the machine part?")
  EngArray2.append("Could you tell me how to turn on this computer terminal?")
  EngArray2.append("Mr. Tanaka authorized this construction project, didn't he?")
  EngArray2.append("Is there still work to be done on the annual report?")
  EngArray2.append("Isn't there a warranty on this copy machine?")
  EngArray2.append("The prices on summer clothing have been marked down, haven't they?")
  EngArray2.append("Did you sort out the requisitions from the supplier?")
  EngArray2.append("Shall I go and ask our manager to drop a new agreement?")
  EngArray2.append("Can you locate the filing cabinet in the storage room?")
  EngArray2.append("What's the name of the party you're calling?")
  EngArray2.append("What are my promotion prospects?")
  EngArray2.append("Have you prepared the diagrams to show the sales figures?")
  EngArray2.append("Are you going to put in for the transfer?")
  EngArray2.append("Do you think Mr. Yun will give me the benefit of the doubt?")
  EngArray2.append("Do you want the figures excluded in the weekly report?")
  EngArray2.append("How was the evaluation from your immediate supervisor?")
  EngArray2.append("Which contractor is offering the most reasonable bid?")
  EngArray2.append("Who is going to be assigned to take on the new task?")
  EngArray2.append("Would you like a tour of our manufacturing plant in Thailand?")
  EngArray2.append("What time would you like to dine?")
  EngArray2.append("Have the sales projection on my desk first thing in the morning.")
  EngArray2.append("I'm afraid I can't make Monday.")
  EngArray2.append("The seminar was rescheduled for Friday.")
  EngArray2.append("I am supposed to take several days off.")
  EngArray2.append("Do you think I can withdraw some money from the ATM downstairs now?")
  EngArray2.append("I'd like to confirm my reservation for tomorrow night.")
  EngArray2.append("Our new office is more spacious than I expected.")
  EngArray2.append("We are two days behind schedule.")
  EngArray2.append("I'm sorry, but the shirts in the smaller size are out of stock.")
  EngArray2.append("If you come up with any good ideas for the advertisement, just let me know.")
  EngArray2.append("The presentation by Mr. Ito will not begin for another twenty minutes.")
  EngArray2.append("I hear our headquarters will be relocated to Florida next year.")
  EngArray2.append("Why did you turn down the job offer from Nakano Corporation?")
  EngArray2.append("I've just placed an order for those office supplies you asked me to get.")
  EngArray2.append("We are running out of gas, so let's stop at a gas station.")
  EngArray2.append("I couldn't make it to the meeting because my flight was delayed.")
  EngArray2.append("Please hold while I transfer your call.")
  EngArray2.append("Will you show me your resume?")
  EngArray2.append("I have to finish the quarterly report before taking a break.")
  EngArray2.append("Do you take out a subscription to the art magazine?")
  EngArray2.append("I need to have someone pick Mr. Ito up at the airport.")
  EngArray2.append("My boss and I can't get along well with each other.")
  EngArray2.append("I'm not sure if Dr. Moore has an opening in the afternoon next Tuesday.")
  EngArray2.append("I can't seem to finish this report by tomorrow because of my heavy workload.")
  EngArray2.append("Our parts supplier will go on strike the week after next.")
  EngArray2.append("Do you think you could possibly fill in for me next week?")
  EngArray2.append("I forwarded the e-mail from Samson Co. to you.")
  EngArray2.append("Tom has been in a meeting. I'm afraid he can't make it on time.")
  EngArray2.append("Did you figure out why the concert had been called off?")
  EngArray2.append("Give me a ring when your flight to London is completely booked up.")
  EngArray2.append("Have you already filled out the form for supplementary funds?")
  EngArray2.append("Credit cards will have to do.")
  EngArray2.append("I look forward to working with you soon.")
  EngArray2.append("Sir, I can fit you in at 8:30 in the morning tomorrow.")
  EngArray2.append("I can't get this vacuum cleaner to work.")
  EngArray2.append("I'm screening applications for the position of chief administrative officer.")
  EngArray2.append("Ms. Whitman has been on leave from work for a while, hasn't she?")
  EngArray2.append("How much time are we allotted to implement the project?")
  EngArray2.append("Please submit your claim form to our manager with a receipt attached.")
  EngArray2.append("Show me some form of identification or a major credit card, please.")
  EngArray2.append("We need to hammer out a solution by the end of the week.")
  EngArray2.append("I'm looking for a birthday gift for my business associate.")
  EngArray2.append("I don't think the workload is properly allocated.")
  EngArray2.append("We should expedite our plan because the current situation won't last long.")
  EngArray2.append("Mr. Jason came down with a bad cold.")
  EngArray2.append("I'm afraid we made a wrong turn because I'm not familiar with this area.")
  EngArray2.append("The specification form is due Saturday morning, isn't it?")
  EngArray2.append("We have to find a temporary replacement immediately.")
  EngArray2.append("I think we should cut output when sales pick up.")
  EngArray2.append("The committee meeting is set for Thursday afternoon.")
  EngArray2.append("We are on a tight budget and have to cut corners.")
  EngArray2.append("We are short of letterhead stationery.")
  EngArray2.append("How's your job search coming along?")
  EngArray2.append("How was the turnout at the annual meeting yesterday?")
  EngArray2.append("Where is the home appliances department?")
  EngArray2.append("I appreciate your advice. It certainly paid off.")
  EngArray2.append("This two-story house will be remodeled soon.")
  EngArray2.append("Because of the strike at the factory, our work has come to a standstill.")
  EngArray2.append("Can you tell me where I can get a compensation request form?")
  EngArray2.append("Ms. Marcus asked me to redo all the figures.")
  EngArray2.append("I read great reviews of the play in the newspaper.")
  EngArray2.append("We don't have enough left in our budget.")
  EngArray2.append("Will you accept foreign currency?")
  EngArray2.append("I was told to have an annual physical check-up.")
  EngArray2.append("What's the value of the content?")
  EngArray2.append("I'm working on the charts for my presentation.")
  EngArray2.append("To whom should I submit my request for time-off?")
  EngArray2.append("How's your new project coming along? I'm only halfway done.")
  EngArray2.append("I saw your products advertised in the paper.")
  EngArray2.append("Mr. Lee has purchased 150 shares of blue-chip stock.")
  EngArray2.append("I think Mr. Newman is overqualified for that job.")
  EngArray2.append("Who is taking over our foreman's job?")
  EngArray2.append("How can we raise our product visibility?")
  EngArray2.append("It's lucky the landscaping firm has offered to lease us some storage space.")
  EngArray2.append("Instead of doing some hiring, we should increase our advertising budget.")
  EngArray2.append("Has the outgoing mail been sorted yet?")
  EngArray2.append("I'd like to have this package sent to Boston by snail mail.")
  EngArray2.append("There is some kind of malfunction with the heating system in my office.")
  EngArray2.append("Just a reminder that the building we are in is conducting a fire drill tomorrow.")
  EngArray2.append("I'll call Sam in Personnel and see what he can do about the hiring.")
  EngArray2.append("I would like to introduce today's keynote speaker, Mr. Spielberg.")
  EngArray2.append("On behalf of all the employees, I would like to propose a toast to the new chairman.")
  EngArray2.append("Further information about the event is available on our website.")
  EngArray2.append("Designing our homepage with great care will surely benefit us in the long run.")
  EngArray2.append("The recent surge in computer sales has also increased demand from our customers.")
  EngArray2.append("It is privilege to be able to work with Mr. Ellison.")
  EngArray2.append("We offer low monthly payments and no annual fees.")
  EngArray2.append("Stay tuned for further traffic updates.")
  EngArray2.append("If you follow these guidelines, you'll be receiving a higher salary than ever.")
  EngArray2.append("Please join me in welcoming Dr. Harrington from Kingdom University.")
  EngArray2.append("All passengers who are flying on TFA 106 should now proceed to Gate 17B.")
  EngArray2.append("Proceeds will be donated to the children's hospital.")
  EngArray2.append("We apologize for any inconvenience this may cause and appreciate your patience.")
  EngArray2.append("Before we start our tour, I'd like to briefly review our agenda for today's activities.")
  EngArray2.append("Please be reminded that the dining hall has a limited capacity.")
  EngArray2.append("Please refer to the complimentary airline magazine for a complete list of in-flight shopping items.")
  EngArray2.append("Ladies and gentlemen, please give Mr. Wagner a big hand.")
  EngArray2.append("We regret to announce that flight 078 has been delayed due to the inclement weather conditions.")
  EngArray2.append("MPM is celebrating its 30th anniversary this May with some in-store entertainment following the award banquets.")
  EngArray2.append("Should you have any questions, please do not hesitate to contact us.")
  EngArray2.append("In order to finalize your reservation, I need a deposit of $150 soon.")
  EngArray2.append("Please have your order and payment ready when the attendant reaches you.")
  EngArray2.append("I want to acknowledge the group of engineers who worked with me.")
  EngArray2.append("You will all benefit from Ms. Fox's wealth of experience as a leading psychologist.")
  EngArray2.append("Please note that payment can be made by credit card only.")
  EngArray2.append("We would like to inform you that your travel arrangements have all been confirmed.")
  EngArray2.append("Mr. Dell's contributions to the food industry over the years have been remarkable.")
  EngArray2.append("In accordance with new city regulations, we will upgrade our facilities for the disabled.")
  EngArray2.append("Afternoon sessions are on the third floor, and a luncheon will be served in the Ohana room.")
  EngArray2.append("To protect the delicate habitat, refrain from picking flowers near the falls.")
  EngArray2.append("This announcement is for those who are interested in Asian cuisine.")
  EngArray2.append("I'm calling in reference to the appointment with Mr. Fox.")
  EngArray2.append("You have reached D&S Real Estate.")
  EngArray2.append("You can register for a job-hunting seminar during regular office hours.")
  EngArray2.append("Don't miss this family event this coming Sunday at the community center.")
  EngArray2.append("In the event of emergency, you must follow the evacuation procedures.")
  EngArray2.append("Don't forget to put the lid down when you use a copier.")
  EngArray2.append("This afternoon, we are going to conduct a test of the air conditioning system.")
  EngArray2.append("Our company will soon launch a recycling program at all our locations.")
  EngArray2.append("I want to reschedule my appointment due to an unexpected out-of-town meeting.")
  EngArray2.append("Due to renovation, the toy store will not be open until the end of this month.")
  EngArray2.append("Passengers should proceed to the airline counter to receive complimentary vouchers covering overnight lodging at a nearby hotel.")
  EngArray2.append("The meteorological agency has asked local radio stations to issue a storm warning.")
  EngArray2.append("There is priority seating for the elderly and the physically challenged.")
  EngArray2.append("Portable appliances must be turned off prior to ascent.")
  EngArray2.append("The installation of a new heating apparatus is going to begin this weekend.")
  EngArray2.append("If you purchase any product worth over $400, we'll deliver it free of charge.")
  EngArray2.append("The hearing was adjourned until the following day.")
  EngArray2.append("Our guest today is Mr. Ted Lucas, a specialist in energy-efficient lighting fixtures.")
  EngArray2.append("We offer a variety of options to ensure that you have no problems with pest control.")
  EngArray2.append("Effective next week, all employees must wear safety glasses when entering the lab.")
  EngArray2.append("The property is already wired for a computer network.")
  EngArray2.append("Most airlines have recently changed their policy regarding non-refundable tickets.")
  EngArray2.append("Donations were up 10% from the previous year, most likely due to growing public concern about environmental protection.")
  EngArray2.append("We are happy to announce that we will provide free delivery within the city limits.")
  EngArray2.append("Events such as book signings and performances of classical music will be held to complement the exhibition.")
  EngArray2.append("Since our overseas sales have risen sharply, we can expect an overall increase in earnings in the next quarter.")
  EngArray2.append("In case of fire, wear safety goggles and properly use the fire extinguisher.")
  EngArray2.append("Our experienced certified accountant can answer questions you have.")
  EngArray2.append("Ms. Taylor is available to get you and your family settled in with less difficulty.")
  EngArray2.append("Periodical maintenance of the machine is highly recommended.")
  EngArray2.append("All the employs are obliged to wear a helmet in the factory.")
  EngArray2.append("The price of gasoline varies from region to region.")
  EngArray2.append("Contrary to the weather forecast, it cleared up and got so hot that I regretted wearing a sweater.")
  EngArray2.append("The operational manual of the system is stored in the office for future reference.")
  EngArray2.append("A number of small companies in a competitive market end up in bankruptcy.")
  EngArray2.append("The CEO offered his resignation because profits were down for three years in a row.")
  EngArray2.append("The client was advised to read the small print before signing the contract.")
  EngArray2.append("Customers are entitled to return items within 10 days of purchase.")
  EngArray2.append("The recent surge in salse is attributed to the growing needs for our product in the market.")
  EngArray2.append("Upon completion of the development of the product, we will advertise it in the market.")
  EngArray2.append("Due to a series of accidents, the company implemented safety regulations.")
  EngArray2.append("Psy-tech Info is dedicated to providing quality and sophisticated products.")
  EngArray2.append("Overnight delivery is subject to an additional fee.")
  EngArray2.append("The new regulations will come into effect in April.")
  EngArray2.append("The merchandise can be purchased by means of a bank transfer.")
  EngArray2.append("Please be aware that we accept online applications only.")
  EngArray2.append("The flagship product accounts for 40% of the company's revenue.")
  EngArray2.append("You are responsible for the loss of your valuables during the concert.")
  EngArray2.append("The Amsterdam Hotel can accommodate a large tour group.")
  EngArray2.append("With the new equipment, production will be significantly increased.")
  EngArray2.append("Mr. Wood is fully qualified for the job.")
  EngArray2.append("Should you have any questions about our products, please contact us.")
  EngArray2.append("If you think you cannot meet the deadline, speak with your boss.")
  EngArray2.append("Given the way our sales representatives talk, a large decline in sales can be expected.")
  EngArray2.append("Our instructional video features exercise routines demonstrated by professionals.")
  EngArray2.append("Where is the venue for the plenary session held in May?")
  EngArray2.append("Marvin Motors will cease their business operations effective September 30.")
  EngArray2.append("Keep all harmful substances out of children's reach and sight.")
  EngArray2.append("A temporary alternative plan to reduce operating expenses was presented in the meeting.")
  EngArray2.append("Mr. Hom is so upset because his transfer to India was confirmed without notice.")
  EngArray2.append("Promotional flyers and posters are indispensable to this project.")
  EngArray2.append("The company announced that the insurance premium would be raised.")
  EngArray2.append("Other than software development, our company assumes responsibility for delivery.")
  EngArray2.append("For your convenience, we have installed a vending machine in the lounge.")
  EngArray2.append("The reduction in benefits and salaries will affect the quality of employees' work.")
  EngArray2.append("Customer service agents are required to comply with the regulations in the manual.")
  EngArray2.append("Due to the disappointing economic outlook, no more investments will be made.")
  EngArray2.append("Enclosed please find a copy of the design specifications provided for your use.")
  EngArray2.append("We recommend that you consider using complementary treatment such as acupuncture.")
  EngArray2.append("The company has decided to curtail the production line.")
  EngArray2.append("A number of economic analysts claim that rapid growth for the computer market cannot be expected in the foreseeable future.")
  EngArray2.append("Before going any further, we need to conduct a survey to decide whether our product is practical and marketable.")
  EngArray2.append("The Diet enacted a law yesterday that protects personal information from birthdays to addresses.")
  EngArray2.append("The board of directors agreed unanimously on launching a market research project.")
  EngArray2.append("There are several positions in our company that report directly to the vice president.")
  EngArray2.append("The upcoming expo will showcase state-of-the-art Internet technology.")
  EngArray2.append("The unemployment rate has been increasing on account of the economy.")
  EngArray2.append("The company allocated a sufficient budget for product development.")
  EngArray2.append("Despite the ad campaign we started last month, we have yet to see an increase in sales.")
  EngArray2.append("Info Second has been concerned about its increasing employee turnover.")
  EngArray2.append("Baggage that is left unattended and looks suspicious will be opened and examined.")
  EngArray2.append("On average, the company increased sales by 20% annually for the past 4 years.")
  EngArray2.append("The hotel is going to be used for private business functions.")
  EngArray2.append("The information can be acquired extraneously, not directly through the firm.")
  EngArray2.append("When Mr. King got promoted, he immediately put in for a raise.")
  EngArray2.append("The budget allocated to advertising is quite limited.")
  EngArray2.append("Ms. Tucker's knowledge as a banker will be drawn on as negotiations proceed.")
  EngArray2.append("Police will confiscate illegal gambling profits generated by sports betting.")
  EngArray2.append("Employee volunteers can alleviate temporary staff shortages.")
  EngArray2.append("The fashion designer's career culminated at the sold-out fashion show.")
  EngArray2.append("Because of the road closing, detour signs are supposed to be installed around the site.")
  EngArray2.append("We have to handle the transaction records with caution.")
  EngArray2.append("The harvesting machine is under warranty for two years covering all parts and labor.")
  EngArray2.append("In observance of Children's Day, the nursery will be closed on Monday.")
  EngArray2.append("If you'd like to check your balance, please enter your password and press 2.")
  EngArray2.append("My colleagues want to express their condolences to the family of the deceased.")
  EngArray2.append("Employees who keep exemplary records will be given commendations.")
  EngArray2.append("Employees are encouraged to wear formal business attire at the banquet.")
  EngArray2.append("Due to time constraints, Mr. Starr didn't get around to finishing his annual report.")
  EngArray2.append("Ms. Barker, the chief engineer, has unlimited access to the computer files.")
  EngArray2.append("The state of Florida is taking measures to protect its people from tropical storms.")
  EngArray2.append("Any violation of the company's Ethics Policy is subject to an appropriate penalty.")
  EngArray2.append("Expense vouchers must be filled out and copied in triplicate.")
  EngArray2.append("We would be greatly appreciative of your comments regarding our services.")
  EngArray2.append("Mr. Wade will be asked to express his opposing point of view regarding the plan.")
  EngArray2.append("Ms. Lee will host an internationally renowned dignitary at the ceremony.")
  EngArray2.append("Our school's foreign study programs serve to foster positive international goodwill.")
  EngArray2.append("Upon closer inspection of the delivered goods, we found some defective items in them.")
  EngArray2.append("Members of the implementation team will be endorsed by the office of Marketing Communications.")
  EngArray2.append("It is obvious that the marketing campaign of the competitor is superior to ours.")
  EngArray2.append("The terrible automobile accident occurred in the middle of the intersection.")
  EngArray2.append("Prior to the presentation, check the document thoroughly once again for errors.")
  EngArray2.append("Please make sure that all the lights are turned off before you leave.")
  EngArray2.append("This software makes it possible to download music from the Internet.")
  EngArray2.append("Cancellations must be received in writing no later than 7 days prior to the session.")
  EngArray2.append("If you would like to exhibit your products, register now and take advantage of our special rates.")
  EngArray2.append("The carburetor of the truck has to be fixed regardless of the high cost involved.")
  EngArray2.append("We are sorry to inform you that your requested book is already out of print.")
  EngArray2.append("Those who want to buy office supplies in bulk must submit a request form by next week.")
  EngArray2.append("It is strictly prohibited to take photographs without permission within the premises for personal or commercial purposes.")
  EngArray2.append("Hotel guests should refrain from removing fixtures in the room.")
  EngArray2.append("The development of computer-operated assembly lines is one of the crucial innovations over the past decade.")
  EngArray2.append("The sales manager greatly contributed to the sharp rise in sales.")
  EngArray2.append("Art collectors often ask artists to produce art on commission.")
  EngArray2.append("According to a report, over 50 percent of the nation's schools have poor ventilation.")
  EngArray2.append("Reports from the board of trustees are available in HTML format.")
  EngArray2.append("Given the excellent job prospects in the IT industry, she got a job with NSA Copac, Inc.")
  EngArray2.append("Changing jobs at the time was simply not in Mr. Wong's best interest.")
  EngArray2.append("The Minister of Agriculture has encouraged farmers to make use of available technology to move the sector forward.")
  EngArray2.append("After filling in the registration form, kindly return it with a check payable to Westland Dance School.")
  EngArray2.append("A new report finds some evidence that small schools are superior to big schools in terms of student achievement.")
  EngArray2.append("The new database was never able to live up to the high expectations.")
  EngArray2.append("According to work rules, all employees are to be informed of their dismissal at least a month in advance.")
  EngArray2.append("During the election year, qualified voters watch television news shows on a daily basis.")
  EngArray2.append("The ideal candidate must be skilled in data management.")
  EngArray2.append("Automation and better fertilizers will make up for the decrease in farm labor.")
  EngArray2.append("The aim of the foundation is to pay tribute to talented individuals who bring joy to millions through their music performances.")
  EngArray2.append("Corrections in sales reports are scheduled to be made either at the end of this month or at the beginning of next month.")
  EngArray2.append("Instead of leaving your e-mail unanswered for days, try to reply to it in a timely manner.")
  
  
  
}
