//
//  EnglishText.swift
//  Eng_shuffle
//
//  Created by tanakat on 2017/06/17.
//  Copyright © 2017年 tanakat0516. All rights reserved.
//

import Foundation

func setSentence() {
  
  JpnArray1[0] = "個人の意志は尊重されなければいけない。"
  JpnArray1.append("気楽にいけよ。大丈夫、すべてうまくいくさ。")
  JpnArray1.append("悲観的な人生観を捨てて、前向きな態度を常に持ち続けよう。")
  JpnArray1.append("生まれた国、性別、信条に関係なく、誰に対しても公平でなくてはならない。")
  JpnArray1.append("平等は憲法で守られている。")
  JpnArray1.append("彼は柱に寄りかかって、自由の女神像をじっとみつめた。")
  JpnArray1.append("香水のほのかな香りを漂わせながら一人の女性が僕の前を通り過ぎた。前の彼女のことを思い出してしまった。")
  JpnArray1.append("納豆は臭いはひどいけれど味は最高。")
  JpnArray1.append("汗でびしょぬれだよ。こないで！臭いわ。シャワーを浴びて。")
  JpnArray1.append("ボブはひどく取り乱していて、現実と虚構の区別がほとんどできなかった。")
  JpnArray1.append("まもなく出版になる彼の小説は、散文に彼の詩の才能を融合させたものだ。")
  JpnArray1.append("来月、その百科事典の最新版が出る。")
  JpnArray1.append("山田さんがその心ひかれるおとぎ話をやさしい日本語に翻訳した。")
  JpnArray1.append("以下の一節は有名な寓話からの引用です。")
  JpnArray1.append("現代文学に詳しいですか？　ほとんど知りません。")
  JpnArray1.append("時々、curve（曲線）とcarve（～を彫る）を混同してしまう。")
  JpnArray1.append("恥ずかしがらないで。あなたの発音は大体あっています。")
  JpnArray1.append("この記事には語彙を本気で増やしたいと思う人々に役立つ情報が含まれています。")
  JpnArray1.append("彼の最新の作品が市庁舎で展示されているの。言葉にできないほど素敵よ。")
  JpnArray1.append("少しつめていただけませんか？ あ、ごめんなさい。こんなに場所をとっていたなんて気づきませんでした。")
  JpnArray1.append("この不恰好な物体は何？ これは抽象芸術の作品だよ！")
  JpnArray1.append("１００ドル貸してくれとリッチーに頼んだら、彼は俺もお金がないんだよ！と言って首を横に振った。")
  JpnArray1.append("安売りをしているといつも衝動買いをしてしまうたちです。 私も。")
  JpnArray1.append("実際のところ、普通の人々にはそんなぜいたく品を購入する余裕はない。")
  JpnArray1.append("予期していた通り、失業率は３四半期連続で上昇した。")
  JpnArray1.append("出費を切り詰めないと。だから、これからは使ったお金は一日単位で記録していくつもりだ。")
  JpnArray1.append("いずれにせよ、組合側はある程度妥協しなければならい。")
  JpnArray1.append("有能な整備士は引っ張りだこだから、なかなかの賃金を稼げる。")
  JpnArray1.append("大統領は福祉改革を実行するための具体的な計画を発表した。")
  JpnArray1.append("彼の政策はきっと暗い結果を招くだろう。徹底的な見直しが必要だ。")
  JpnArray1.append("社会の高齢化が避けられないことは言うまでもない。")
  JpnArray1.append("この表をご覧になってください。少年非行が深刻な割合で増加していることを示しています。")
  JpnArray1.append("多くの商業地区では、数年間売りに出されている空き地がたくさんある。")
  JpnArray1.append("大都市の人口密度が徐々に低下している。")
  JpnArray1.append("ほぼ間違いなくこの先数年、出生率は減少の一途をたどるだろう。")
  JpnArray1.append("その発電所は遠く離れた郡に電気を供給している。")
  JpnArray1.append("許可なくこの装置を操作することはできません。")
  JpnArray1.append("実は、住民たちは放射能にさらされてきた。")
  JpnArray1.append("核エネルギーの潜在的な危険性は，いくら強調してもし過ぎるということはない。")
  JpnArray1.append("過去数年間その問題を見過ごしていた報道機関が，今ではどちらかと言えばそのことを重視し過ぎている。")
  JpnArray1.append("穀物を栽培するだけでなく，その農場経営者は食料雑貨店も経営している。")
  JpnArray1.append("その研究所は1960年代後半に設立された。")
  JpnArray1.append("スターさんに直接相談したらどうですか？この辺りでは文句なしでいちばん有名な弁護士ですよ。")
  JpnArray1.append("念のためにメモしておきます。記憶力が悪いから。")
  JpnArray1.append("弁護士は依頼人に，保険会社に対して法的手段を取ることを勧めた。")
  JpnArray1.append("彼らには，けがに対する補償を受ける権利がある。")
  JpnArray1.append("インフルエンザの流行で，現在までに200人もの人が亡くなっている。")
  JpnArray1.append("それらの錠剤の効果は強烈だが持続性はない。")
  JpnArray1.append("彼は爪を噛む癖がある。あれには本当にぞっとするよ。")
  JpnArray1.append("うちの息子を抱こうとしてかがんだときに、おばあちゃんは腰を痛めた。")
  JpnArray1.append("肩が凝るなら、薬草治療を試してごらんよ。")
  JpnArray1.append("医学の飛躍的発展は人類全体に多大な恩恵をもたらしてきた。")
  JpnArray1.append("クローン技術は人間にはもちろん、牛にも応用してはいけない。絶対にしてはならないことだ。")
  JpnArray1.append("鯨は哺乳動物に分類される。")
  JpnArray1.append("進化論は私の想像力の範囲を超えている。")
  JpnArray1.append("その生物学者は自分の歴史的発見に誇りを持っており、そのことを臆することなく口に出す。 ")
  JpnArray1.append("倫理的な理由から、彼らはいわゆる遺伝子治療に反対している。")
  JpnArray1.append("その病気の初期症状は高熱と喉の痛みです。")
  JpnArray1.append("脳の構造は複雑だ。")
  JpnArray1.append("病気のために年次会議を欠席した代表者もいた。")
  JpnArray1.append("私の娘婿は徐々に胃がんを克服しつつあり、今は明るく元気だ。")
  JpnArray1.append("これって偽者だろう？ 何言ってるの。本物の骨董品よ。 まさか！")
  JpnArray1.append("他にご注文は？ それだけです。こちらでお召し上がりですか？ 持ち帰ります。")
  JpnArray1.append("この敷物はおいくらですか？ 税込みで１００ドルです。じゃあ、これにします。")
  JpnArray1.append("そのパンツはあなたには似合わないと思う。こっちをはいてみて。今すごく流行っているのよ。")
  JpnArray1.append("彼はおつりはいいですと言って、急いでタクシーを降りた。")
  JpnArray1.append("当店のお客様は、わずかな追加料金で配達サービスをご利用できます。")
  JpnArray1.append("これは僕のおごり。だめよ。外食のときはいつもおごってもらっているし。うーん、わかった。じゃあ割り勘にしよう。")
  JpnArray1.append("ショッピングセンターをぶらぶらしていたら、偶然ケンに会った。")
  JpnArray1.append("現金が足りなかったので、先週口座にいれた１００ドルを引き出した。")
  JpnArray1.append("彼女は帰宅途中にハンドバックを奪われた。")
  JpnArray1.append("それは変だわ。どうしてそんなことが起きたのか教えて。後で説明するよ。")
  JpnArray1.append("私が約束を破ったので、罰として両親に門限を6時にされた。")
  JpnArray1.append("ことわざにある通り、嘘も方便(目的が手段を正当化する)")
  JpnArray1.append("誰も頼れる人がいないとわかったのだから、自分の力でやっていくしかない｡")
  JpnArray1.append("議長は私の話を遮って、話し合いはここまでにして決を採りましょうといった。")
  JpnArray1.append("我々は会議で素直な意見を交わしたが、この件に関してはまだ全体の意見がまとまらない。")
  JpnArray1.append("あなたは彼と同じ意見？　それとも違うの？彼の方を支持するよ")
  JpnArray1.append("厳密に言えば、彼の見解は私のものとはいくらか異なる。")
  JpnArray1.append("もう一度詳しく説明して頂けませんか？お話の意図が分かりませんでした。")
  JpnArray1.append("僕の案を支持してくれる人は最初は誰もいなかったけれど、最後にはみんなを説得して賛同してもらうことが出来た。")
  JpnArray1.append("君の不屈の努力、勇気、そして知恵には感心するよ。お世辞でもうれしいわ！")
  JpnArray1.append("どうするかを決めるとき、僕は論理ではなく本能を当てにする。")
  JpnArray1.append("彼は独創的かつ賢明な解決案を考え出し、ただちにそれを実行に移した。")
  JpnArray1.append("客観的に見れば、前者は後者よりも劣っている。")
  JpnArray1.append("あなたの考えは理論上は素晴らしそうだけれども、実際には機能しないと思います。")
  JpnArray1.append("私達は彼が相手に勝つことを期待したが、彼はその期待に応えられなかった。")
  JpnArray1.append("皮肉なことだが、彼らの最善の努力にもかかわらず、任務は完全な失敗に終わった。")
  JpnArray1.append("実地経験の不足は彼女の天賦の才能で補える。")
  JpnArray1.append("彼女にはどんな障害をも克服できるすばらしい能力がある。")
  JpnArray1.append("あなたの強固な支援がなかったら、その取引は成立しなかったでしょう。感謝しています。")
  JpnArray1.append("機内への可燃物の持ち込みは禁止されています。")
  JpnArray1.append("ちょっとした事故が原因で私達のウィーン行きの便に遅れが出た。")
  JpnArray1.append("飛行機が爆発して海に墜落し、乗っていた全員が死亡した。")
  JpnArray1.append("彼らは昼夜休むことなく、その墜落事故の原因を調査している。")
  JpnArray1.append("不幸にも、その大惨事で生き残った乗客はほとんどいなかった。")
  JpnArray1.append("航空評論家が統計を詳細に分析した。")
  JpnArray1.append("全従業員を代表致しまして、犠牲者の方々に対してお悔やみを申し上げたいと存じます。")
  JpnArray1.append("ある意味、その惨事の責任は彼にある。")
  JpnArray1.append("車両は欠陥がないか三ヶ月に一度検査される。")
  JpnArray1.append("うちの光熱費がそんな額になっているのを知ってびっくりした。")
  JpnArray1.append("水道の栓を閉めなさい！とお母さんがかんかんになって叫んだ。")
  JpnArray1.append("食べ物が腐れないように蓋をしっかり閉めなさい。")
  JpnArray1.append("ハサミを貸してもらえる？もちろん。はいどうぞ。")
  JpnArray1.append("針と糸の代わりに透明な接着剤を使っても結構です。")
  JpnArray1.append("この織物を染めたら縮んでしまった。")
  JpnArray1.append("この革のジャケットは処分するよ。両肘の部分がすり減って穴があいているから。")
  JpnArray1.append("その混ぜ合わせたものに小麦粉を加えて、とろみがつくまでかき混ぜましょう。")
  JpnArray1.append("残り物をどうしょう？とりあえず冷蔵庫に入れておいて。後でレンジで温め直すよ。")
  JpnArray1.append("新しいパソコンに全額つぎ込む事もできたが、考え直してまさかの時のために多少は残しておくことにした。")
  JpnArray1.append("携帯電話はちょっとした必需品になったことだし、それなしではやっていけない。")
  JpnArray1.append("イスにゆったり座ってくつろいだ途端、妻に雑用を頼まれた。")
  JpnArray1.append("彼女は赤ちゃんを寝かせて自分も隣に横になった。")
  JpnArray1.append("ここにあるものを片付けなさい。邪魔よ。")
  JpnArray1.append("子供達が恐竜ごっこをしていたら、お母さんに叱られた。")
  JpnArray1.append("彼が棚にぶつかり、とても高価な陶磁器が落ちて粉々に割れてしまった。")
  JpnArray1.append("うちの子たちをちょっと見ててもらえる？　ケンを向かえに行かないといけないの。いいよ")
  JpnArray1.append("隣の家の人が庭をめちゃくちゃにされたと、私達にがみがみ説教した。")
  JpnArray1.append("ドリーはあらゆる面でお姉さんにそっくりだ。二人を見分けることはできないよ。")
  JpnArray1.append("概して、双子には似たところが多い。")
  JpnArray1.append("皿洗いとか洗濯とか、そういうことにはもううんざり！")
  JpnArray1.append("時間があいたときの一番の楽しみは浜辺の散歩です。気持ちいいですよ。")
  JpnArray1.append("私、もうくたくた。日陰で休憩しましょう。そうだね。")
  JpnArray1.append("ボブ、この自動販売機、故障しているわ。なんだって！喉が渇いて死にそうだよ！")
  JpnArray1.append("彼は空腹と疲労で気を失ったが、しばらくして意識を取り戻した。")
  JpnArray1.append("たった一つの家具を除けば、講堂はがらんどうだった。")
  JpnArray1.append("家賃が安ければ、どんなマンションでも構いません。こだわりは有りませんから。")
  JpnArray1.append("彼の60歳のいとこが湖畔の不動産を相続した。")
  JpnArray1.append("雑談はこの辺にして、本題に入りましょう。")
  JpnArray1.append("ルーシーは、契約書にサインさせようとする強引な販売員に腹を立てた。")
  JpnArray1.append("私達の株式投資への意欲をそぐような要因がかなりある。")
  JpnArray1.append("日本は様々な原料を輸入し、工業製品を輸出している。")
  JpnArray1.append("経済発展の過程で、日本はその伝統的価値観を捨ててきた。")
  JpnArray1.append("世界はかつて無い危機に直面している。")
  JpnArray1.append("要するに、その規制の目的は国内産業の保護だ。")
  JpnArray1.append("世界での競争力を維持するためには、日本は大幅な規制緩和に真剣に着手しなければならない。")
  JpnArray1.append("危機にさらされ、わらにもすがる思いでいる人々を、私達は放っておけない。")
  JpnArray1.append("議会は発展途上諸国に財政援助を行うことを決議した。")
  JpnArray1.append("英国の君主制は廃止されるべきだと言う人もいるけど、あなたはどう思う？")
  JpnArray1.append("彼らは攻撃を逃れる安全な場所を探したが、隠れる場所はどこにもなかった。")
  JpnArray1.append("軍縮において、両国が大きな進展を遂げる見込みはほとんどない。")
  JpnArray1.append("交渉は進行中だ。そろそろ正念場を迎えるだろう。")
  JpnArray1.append("奴隷たちは自分たちの運命を変えたいと切望していた。")
  JpnArray1.append("貴族達は思うがままに特権を乱用した。")
  JpnArray1.append("結局、革命それ自体は何の成果ももたらさなかった。")
  JpnArray1.append("ボブがそれには反対だ！と言って会話に割り込んできた。けれども、誰も耳を貸さなかった。")
  JpnArray1.append("私達は彼の順番をわざと飛ばした。")
  JpnArray1.append("誰かがいじめられているのを見たのに、彼は見ないふりをした。")
  JpnArray1.append("ニックと僕がテストでカンニングしたとき、僕は停学処分。ニックの方はまんまと逃れた。")
  JpnArray1.append("彼らはリチャードの富と地位に対する嫉妬から、彼に敵意を抱いている。")
  JpnArray1.append("彼のことは大嫌い！　まるで自分が大物であるかのように振る舞うのよ。")
  JpnArray1.append("僕たちが褒め言葉をかけたのに、彼はしかめてそっぽを向いた。失礼だ！")
  JpnArray1.append("その莫大な財産は自分が自由にできるものだ、と彼は主張した。")
  JpnArray1.append("頑固になればなるほど孤立するよ。")
  JpnArray1.append("遠回しな言い方はやめてくれ！　僕にどうしろっていうんだ？慌てずに待つしかありません。時が経てばわかります")
  JpnArray1.append("課題は電子メールで6月10日の午後5時までに提出してください。")
  JpnArray1.append("ジョーが勤勉なんてとんでもない。だからまた数学を落としたんだ。")
  JpnArray1.append("彼の論文は意味不明。第一、主題が曖昧だ。")
  JpnArray1.append("彼の小論文は簡潔で要領を得ていた。")
  JpnArray1.append("この複雑な問題をどう処理するつもり？任せとけって。朝飯前さ。")
  JpnArray1.append("ニック、これを提出する前にざっと目を通して欲しいの。ごめん、今、手が離せないんだ。")
  JpnArray1.append("締め切りに間に合わなかったらどうなる？きっと彼に怒られるぞ！")
  JpnArray1.append("字が汚いことを別にすれば、君に要約は完璧だ。")
  JpnArray1.append("その前提が妥当かどうかよく考えるべきだ。")
  JpnArray1.append("とりわけ、科学用語には厳密な定義が要求される。")
  JpnArray1.append("何よりもまず、公式を暗記しなさい。")
  JpnArray1.append("体積を計算する場合は、縦と横と深さをかけます。")
  JpnArray1.append("樽の底にとても小さなひびがあるのを見つけた。")
  JpnArray1.append("この章では幾何学の概念に焦点ををあてます。")
  JpnArray1.append("フィルは実用的な技能よりも学問的なテーマのほうに興味がある。")
  JpnArray1.append("この顕微鏡、どこかおかしくなっちゃった。修理してもらわないと。見せて。僕が直せるかも。")
  JpnArray1.append("インストゥルメントってなんですか？例えば、温度計や気圧計とかの計器がそうです。")
  JpnArray1.append("その微粒子は肉眼でもかろうじて見える。")
  JpnArray1.append("筋肉組織はおびただしい数の細胞から成っている。")
  JpnArray1.append("この物質は主に水素と酸素でできている。")
  JpnArray1.append("正確な気温はセ氏22.68度です。")
  JpnArray1.append("ナオミは自分の完璧なスタイルをひけらかしたがる。私も彼女みたいに痩せていればなあ。彼女がうらやましいわ。ダイエットすれば")
  JpnArray1.append("ナオミに一目惚れした。三ヶ月後、思い切って彼女にプロポーズしてみたが振られてしまった。")
  JpnArray1.append("偶然その人に出会ったの。優しくて頭もいいの。おまけに独身！")
  JpnArray1.append("彼の甥は、謙虚で思いやりのある人になるように育てられた。")
  JpnArray1.append("私の両親にボブを紹介したら、二人ともすぐに彼のことが好きになった。")
  JpnArray1.append("人は外見ではなく、むしろ中身で判断されるべきだ。")
  JpnArray1.append("大切なのは肩書きなんかじゃない。絶対そうだ！と、ボブは語気を強めて言った。")
  JpnArray1.append("自分の力で成功をつかんだ人が言ったように、先見の明のある人は最後には成功する")
  JpnArray1.append("若さが永遠のものではないことを忘れてはならない。")
  JpnArray1.append("いったいなぜみんながそれ程までにボブを軽蔑するのか、僕にはわからない。")
  JpnArray1.append("彼のことを笑わずにはいられない。ばかな間違いを繰り返すからね。きっと彼は懲りないんだろうな。")
  JpnArray1.append("さらに厄介なことに、彼は私達に迷惑をかけていることさえわかっていない。")
  JpnArray1.append("慌てていたから、手袋を間違えて裏返しにはめてしまった。")
  JpnArray1.append("デイブはデブでドジ。浅い小川を飛び越えた時に、つまずいて足首を捻挫したんだ。")
  JpnArray1.append("僕、高所恐怖症なんだ。弱虫！")
  JpnArray1.append("消極的なその男性が、人前で自己表現をすることはまずない。")
  JpnArray1.append("迷信は全て根拠のないものだということが、ニックに言われてよくわかった。")
  JpnArray1.append("注射のことを考えると、恐くて震えてしまう。")
  JpnArray1.append("ボブは根が怠け者だから、与えられた仕事をしばしば怠る。")
  JpnArray1.append("ボブが働いている間、ジェニファーは家でくだらないメロドラマに夢中になっていた。")
  JpnArray1.append("ボブはマンガ好きだけど、僕にはそれほどいいものとは思えない。実際、つまらないよ。")
  JpnArray1.append("彼が私の目を見ようとしなかったので、何かを隠していると思った。")
  JpnArray1.append("彼女は我慢しきれなくなり、襟首をつかんで彼をののしった。")
  JpnArray1.append("確かに、私達は時々口げんかもしますが、普段は仲良くやっています。")
  JpnArray1.append("君の家に寄ってもいいかい？もちろんいいわよ。気兼ねなく！")
  JpnArray1.append("ちょっと待ってて。すぐ戻るから。切らないでよ！")
  JpnArray1.append("うちには泊められないわ。一つには、時々お父さんがふらっとやって来るから。")
  JpnArray1.append("ジェニファーがじっと立っている間、ボブは歩道を行ったり来たりしていた。")
  JpnArray1.append("仲直りしようよ、リサ。私がいて当然だなんて思わないで。私たち、今度は永遠に終わりよ。本気なんだから！")
  JpnArray1.append("おい！リサ、そう感情的になるなよ。君を傷つけるつもりじゃなかったんだ。じっくり話し合おう。")
  JpnArray1.append("私を裏切ったわね！許してくれよ。どうしたら埋め合わせができるかなあ？仕返ししてやるっ！")
  JpnArray1.append("自分の罪は隠しておかずに告白したほうがいい。")
  JpnArray1.append("約束は守りなさい。そうしないと評判を落としますよ。")
  JpnArray1.append("ボブは自分の道徳的信条を曲げない男だ。正直でいれば最後には報われると信じている。")
  JpnArray1.append("元気を出して。仕方ないわ。やれるだけのことはやったんだ。わかってる。過ぎたことにくよくよしないで。やり直せるわよ！")
  JpnArray1.append("ジェーン、タイムズ・スクェアーまで乗せて行って欲しいんだけど。そうしてあげたいのは山々だけど。今、全然時間がないの。")
  JpnArray1.append("いつものように、マイクは時間通りに現れた。本当に時間に正確な人だ。")
  JpnArray1.append("この前、混雑した幹線道路の真ん中でガス欠してしまった。")
  JpnArray1.append("私の前を走っていたトラックがスリップして横転し、積み荷を路面いっぱいに散乱させた。")
  JpnArray1.append("衝突をさけられたのは運が良かっただけ、と彼は回想した。")
  JpnArray1.append("緊急の際には、すぐに私の代理人と連絡を取って下さい。")
  JpnArray1.append("ジェーン、俺たちはどこに向かってるんだ？迷ったみたい。違う方向に来ちゃったわ。何だよ。車を止めてくれ！")
  JpnArray1.append("僕のさびついたフォードが故障して、交差点をふさいでしまった。")
  JpnArray1.append("表面に細かい傷やへこみがたくさんあるから磨いても無駄だよ。")
  JpnArray1.append("おい。渋滞にはまっちゃったよ！熱くならないで、ジョー。近道しましょう。時間までには着けるわ。")
  JpnArray1.append("パンクしちゃったよ。手を貸してくれる？喜んで。")
  JpnArray1.append("ハンドルがきかなくなった救急車が、危うく歩行者をひきそうになった。")
  JpnArray1.append("火星にはかつて原始的な生物が存在していたと彼は力説している。")
  JpnArray1.append("乗務員たちは宇宙への航海の準備に忙しい。")
  JpnArray1.append("彼らは無重力状態で一連の実験をおこなった。")
  JpnArray1.append("多くの天文学者は、宇宙は無限に膨張を続けていくものと考えている。")
  JpnArray1.append("宇宙飛行士たちは自然と沸き起こった拍手で迎えられた。")
  JpnArray1.append("滅亡の危機に瀕した地球を守ろうと、ある基金が設立された。")
  JpnArray1.append("大洪水で現地の交通網が麻痺した。")
  JpnArray1.append("赤道は地球を二つの半球に分ける。")
  JpnArray1.append("毛皮のコートのために動物を罠で捕獲するのは残酷なことだ。")
  JpnArray1.append("その団体は野生動物の保護において、最も重要な役割を果たしている。")
  JpnArray1.append("多くの弱い生物種が絶滅の危機に瀕している。")
  JpnArray1.append("長引く干ばつが収穫に甚大な被害をもたらした。")
  JpnArray1.append("熱帯雨林の消滅が地球規模で急速に進んでいます。その原因の一つは酸性雨です。")
  JpnArray1.append("地球温暖化は二酸化炭素の排出と直接の関係があると言われている。")
  JpnArray1.append("オゾン層の破壊は環境に影響を及ぼす。")
  JpnArray1.append("委員会は、大気汚染を抑制するために互いに協力し合うよう各国に要請した。")
  JpnArray1.append("溶け続ける氷河を監視するために、人工衛星が軌道に打ち上げられた。")
  JpnArray1.append("石油は天の恵みであると同時に災いのもとでもあると、その生態学者は我々に繰り返し警告してきた。")
  JpnArray1.append("その大陸は化石燃料が豊富だ。")
  JpnArray1.append("その地域は鉱物資源が比較的豊かだ。")
  JpnArray1.append("小麦はこの地域の農業生産高のおよそ３分の２を占めている。")
  JpnArray1.append("良い収穫を得るためには、肥沃な土壌が不可欠だ。")
  JpnArray1.append("湿気の多い気候はその半島の特色です。")
  JpnArray1.append("その活火山は周期的に噴火する。")
  JpnArray1.append("パナマ運河は大西洋と太平洋をつないでいる。")
  JpnArray1.append("ここの地理的特徴は私たちの県のそれと似ている。")
  JpnArray1.append("たいてい、飢饉になると疫病も発生する。")
  JpnArray1.append("壊滅的規模の地震が州都を襲い、数万人の住民が家を失った。")
  JpnArray1.append("気をつけろっ！天井が崩れかけてるぞ！")
  JpnArray1.append("台風は速度を上げて沿岸に接近しそうだと天気予報では言っている。")
  JpnArray1.append("試合が中止になるかどうか、まだ決まらないんだ。それがどうしたの？私にとってはどうでもいいことだわ。")
  JpnArray1.append("霧が濃いね。本当ね。でも、たぶんこのあとは晴れるわ。")
  JpnArray1.append("ほとんどの場合、近代化は西欧化と同一のことと見なされる。")
  JpnArray1.append("都会の文化は多くの人々の目には魅力的に映る。とりわけ、若者にとっては。")
  JpnArray1.append("ＡＩは人工知能の略です。")
  JpnArray1.append("家庭用の電化製品は日に日に便利になっている。")
  JpnArray1.append("私の収入は４人家族を養うには十分でないけれども、それで何とかやっていくしかない。")
  JpnArray1.append("ホームページの人気は内容次第。")
  JpnArray1.append("遅れずについていかなくちゃ。一度遅れをとったら追い付くのは大変だよ。")
  JpnArray1.append("技術は急速に進歩するので、遅れを取らずについていくのは大変だ。")
  JpnArray1.append("ますます多くの人々が、その媒体の双方向的な性質を利用しようと躍起になっている。")
  JpnArray1.append("革新的なものを生み出すこと、それは変わった現象を見逃さない能力と何らかの関係がある。")
  JpnArray1.append("多くの他社が我々の優れた方法を真似している。")
  JpnArray1.append("かつての荒涼とした盆地が、繁栄を謳歌するハイテクビジネスの中心地に変ぼうした。")
  JpnArray1.append("まだ改善の余地はたくさんあるけれども、彼の発明品はあらゆる点で従来の機器よりも優れている。")
  JpnArray1.append("その会社の強さは、他社にない未来志向の戦略によって生み出されている。")
  JpnArray1.append("ソニーはこのスゴイ機器に多岐にわたる機能を統合させた。全米で評判になり始めている商品だ。")
  JpnArray1.append("この道具は何かと便利だから、いつも手元に置いています。")
  JpnArray1.append("一般的に、消費者は質よりも量を選びます。今は全く逆です。")
  JpnArray1.append("明らかにその広告は１０代の若者層をターゲットにしている。")
  JpnArray1.append("現在建設中のその工場は、一日当たり１０００台のビデオデッキを組立てることになる。")
  JpnArray1.append("効率的な機械が肉体労働に取って代わった。")
  JpnArray1.append("当時、その巨大企業が国内の商業を事実上独占していた。")
  JpnArray1.append("制限が解除され、数千の新しい企業が誕生した。")
  JpnArray1.append("ばかげた新事業の結果、彼は破産の危機に瀕している。")
  JpnArray1.append("昨年と比べて、売上の数字だけを見れば事業は上向いている。しかしながら、利益はまだ全く出ていない。")
  JpnArray1.append("海外の支店に転勤することになったよ。えっ。寂しくなるわ。手紙でも下さいね。")
  JpnArray1.append("彼が出張中に、奥さんが男の子の赤ちゃんを出産した。")
  JpnArray1.append("どうやらニックは、自分の負担が増えるからその仕事を引き受けたがらなかったようだ。")
  JpnArray1.append("ボブは今夜、彼女とデートするつもりだったが、残業になってしまった。")
  JpnArray1.append("遅くとも金曜日までには損失の見積もりを出して下さい。何とかやってみましょう。")
  JpnArray1.append("頼りにしてるわ、ニック。大丈夫、きちんとやっておきます。ありがとう。感謝するわ。いいんですよ。")
  JpnArray1.append("彼は上司がそばにいる時は熱心なふりをする。")
  JpnArray1.append("彼は同僚を踏み台にして出世した。恥を知るべきだ。")
  JpnArray1.append("景気の後退が始まると、短期契約社員たちは次々に一時解雇を言い渡された。")
  JpnArray1.append("最近では、多くの人々が職に就きたくても就けないでいる。誰の責任だろう？")
  JpnArray1.append("私も悲観的になってきて、以前は決して気にならなかったことに不安を感じている。")
  JpnArray1.append("今日では、サラリーマンでさえ大変な苦難に直面している。")
  JpnArray1.append("当局は通貨を安定させようと懸命だが、どうにもならない。")
  JpnArray1.append("日本の膨大な赤字を削減することが何よりも緊急を要することだ、という結論に我々は達した。")
  JpnArray1.append("アンケート用紙が無作為に配布された。")
  JpnArray1.append("以下の空欄部分にご記入いただくだけで結構です。（黒または青インクではっきりと書いてください）")
  JpnArray1.append("１０％の割引に加えて、無料のオプションツアーを一つ選択できます。")
  JpnArray1.append("各目的地までの往復料金は下記の通りです。")
  JpnArray1.append("事前に予約の確認をするのを忘れないでね。ええ。")
  JpnArray1.append("遅くとも出発時刻の４５分前には搭乗手続きを必ず完了させて下さい。")
  JpnArray1.append("自分の荷物に名札を付けたけれども、すぐに取れてしまった。")
  JpnArray1.append("これらの小包の重さは平均すると２ポンドです。")
  JpnArray1.append("このビニール製のゴミ袋は有害な化学物質を含んでいません。")
  JpnArray1.append("この懐中電灯は明かりが弱くなってきた。電池を入れ替えないと。")
  JpnArray1.append("すみません。ニューヨーク市街に行くシャトルバスはどの位の間隔で走ってますか？")
  JpnArray1.append("そのモーテルは４００人もの宿泊客を泊められる。")
  JpnArray1.append("このスイートルームは私の持っているマンションの３倍の広さだ。")
  JpnArray1.append("この施設内でのゴミの投げ捨てには、最高５００ドルの罰金が課せられることがあります。")
  JpnArray1.append("あのレストランはいつでも込んでいるから事前に予約をした方がいい。")
  JpnArray1.append("食事の邪魔をして悪いんだけど、ちょっと内密に話がしたいの。後で君のところに行くよ。")
  JpnArray1.append("料理人は彼の信じられないほどの食欲にとても驚いた。")
  JpnArray1.append("下で何が起こっているの？すごく気になるわ。さあ、何だろう。")
  JpnArray1.append("興奮したファンたちが、マイケルを一目見ようと裏口に群がっていた。")
  JpnArray1.append("彼らは有名人と出くわすなり、サインをねだった。")
  JpnArray1.append("海外に行くと必ず、時差ボケと下痢に悩まされる。")
  JpnArray1.append("何だか目まいと吐き気がするよ。顔が真っ青よ。")
  JpnArray1.append("鎮痛剤を飲めば、すぐに頭痛は治ります。")
  JpnArray1.append("何だか体調が悪いなあ。一日休みを取った方がいいわよ。")
  JpnArray1.append("この飲料に含まれている成分には有害なものもある。とりわけ、妊娠中の人にとっては。")
  JpnArray1.append("十分な栄養摂取は幼児の発育にとって極めて重要です。")
  JpnArray1.append("適度な運動は血行をよくする。")
  JpnArray1.append("当分の間は酒を控えるようにと、医者に忠告された。")
  JpnArray1.append("本当に体調を良くしたいし減量もしたいから、毎朝泳ぎに行っています。")
  JpnArray1.append("昨日の夜更かしがたたって、彼はひどい風邪をひいた。")
  JpnArray1.append("外科医に説得されて、彼は臓器移植手術を受けることにした。")
  JpnArray1.append("父が寝たきりなので私たちが交代で面倒を見ています。")
  JpnArray1.append("ジャンクフードの過剰な摂取は早死にの一因になる、というのが我々の仮説だ。")
  JpnArray1.append("政府は感染の拡大を未然に防ぐための適切な措置を取らなかった。")
  JpnArray1.append("その大臣は内閣からの辞任を余儀なくされた。")
  JpnArray1.append("多くの人々は現行の義務教育制度が時代遅れであると考えている。")
  JpnArray1.append("大きな目標を実現するようにと、たくさんの人が私を励ましてくれた。")
  JpnArray1.append("自分の夢を実現させるために、彼は学校を中退して東京を目指した。")
  JpnArray1.append("普段は何をなさってるんですか？大学生です。ハーバードの１年です。専攻は？哲学です。")
  JpnArray1.append("２００１年４月１日から授業料が１０％近く値上げになります。")
  JpnArray1.append("奨学金を申し込もうかどうか悩んでるの。やるだけやってみなよ！")
  JpnArray1.append("彼は慶応大学を卒業するとすぐに家業を継いだ。")
  JpnArray1.append("軍の規律は厳格だから、あなたはそっちの世界には向かないわ。")
  JpnArray1.append("私はどんな犠牲を払ってでも、脚本家で食べていくと心に決めている。")
  JpnArray1.append("彼も大人になって、物事を総合的な視野で見られるようになった。")
  JpnArray1.append("同じような人々からなる私たちの地域社会では、体制に従おうとする意識は不可欠な要素である。")
  JpnArray1.append("会社のためにあくせく働くよりは、我が道を行くほうがいい。型にはまろうとしたって何の得にもならないよ！")
  JpnArray1.append("トムは性格が彼のおじに似ている。つまりその、生まれつきの頑固者。彼は絶対に折れない。")
  JpnArray1.append("機が熟したら、大胆に突き進むんだ！僕がいつもそばにいる。")
  JpnArray1.append("自分の信念を守るためには立ち上がるし、いかなる脅威にも屈しないつもりだ。")
  JpnArray1.append("自分の弱点を克服できさえすればなあ。あなた次第よ。")
  JpnArray1.append("自分の才能を示すために、めったにないこの機会を最大限に利用するべきだ。")
  JpnArray1.append("僕をがっかりさせないよね。信頼しているよ。君ならうまくやれるさ！")
  JpnArray1.append("観客たちは彼女の優雅な演技に感動した。")
  JpnArray1.append("１９９５年、安藤氏は建築における最も権威ある賞を受賞した。")
  JpnArray1.append("逆境をものともせず、マイクはすばらしい偉業を成し遂げた。称賛を受けるのは当然だ。")
  JpnArray1.append("聴衆は彼の説得力のある講義に感銘を受けた。")
  JpnArray1.append("庶民の身から、ジョンは世界的な名声を勝ち取った。")
  JpnArray1.append("彼は戦後に莫大な財産を築いた。")
  JpnArray1.append("彼は以前は裕福で気前もよかったけれど、今ではその日暮らしだ。")
  JpnArray1.append("ニックは決してその報酬に満足していない。彼は自己中心的で欲が深い。")
  JpnArray1.append("全部で２００ドル貸してるのよ、ボブ。いつ返すつもりなの？ごめん。金欠なんだ。またなの？")
  JpnArray1.append("ブライアンが驚いたことに、借金はかなりの額になっていた。")
  JpnArray1.append("過去の栄光にしがみつくのはやめないと、取り残されるわよ。")
  JpnArray1.append("今日の厳しい現実からは逃れられない以上、それに順応しなければならない。")
  JpnArray1.append("繁栄は永遠に続くものではない。つまり、いつかは終わりを迎えるものだ。")
  JpnArray1.append("その職種には相応の資格や能力が必要で、コンピューターが使えることは絶対条件である。")
  JpnArray1.append("この封筒に履歴書も入れて人事部に提出して下さい。")
  JpnArray1.append("物事がうまく行くと信じるなんて君も楽観的だね。可能性はせいぜい５０％だよ。")
  JpnArray1.append("登録用紙は無料で入手できます。")
  JpnArray1.append("この講習会に参加をご希望の方は、今すぐお電話下さい。")
  JpnArray1.append("さらにご質問がありましたら、どうぞご遠慮なくフリーダイヤル１−８００−５５５−１２１２までお電話ください。")
  JpnArray1.append("ボブ、最近どう？最高だよ！就職面接がうまくいったんだ。やったじゃない！")
  JpnArray1.append("研修生たちは彼から与えられた指示がさっぱりわからなかった。")
  JpnArray1.append("一度に二つのことはできないよ。無理に決まってる。一つずつやりなよ。")
  JpnArray1.append("ボブ、彼女の邪魔をしちゃだめだぞ。ちょっかいを出すなよ。と彼は小声で言った。")
  JpnArray1.append("そうやってしつこく彼女を困らせると、彼女も怒り出すぞ。")
  JpnArray1.append("彼はあまりに子供だから誘惑に勝てなかった。")
  JpnArray1.append("ぎゃあぎゃあ言うのはやめて。本当にいらいらするわ。と彼女は叫んだ。")
  JpnArray1.append("ニックに口答えしたって無駄だよ。言ってみりゃ彼は独裁者さ。")
  JpnArray1.append("彼女たちは彼の前ではとても礼儀正しいが、実際には、いつも陰口を叩いている。")
  JpnArray1.append("ニックを軽蔑しているんだろう？とんでもない！尊敬しているわ。")
  JpnArray1.append("彼の絶え間ない侮辱が、彼女の怒りをかき立てた。")
  JpnArray1.append("書類の整理とかお茶くみには、ほとほとうんざり。会社を辞めることに決めたわ！")
  JpnArray1.append("実際、多くの人々が家計のやりくりに苦労している。月々１０万円でどうしたらやっていけるだろう？")
  JpnArray1.append("女性職員が自分たちの日常義務に不満を言うのももっともだ。全くやりがいのない仕事だから。")
  JpnArray1.append("抜本的に事業の再構築をおこなったおかげで、当社の黒字は３倍に膨らんだ。")
  JpnArray1.append("現在の多くの人が、会社に対する忠誠はばかげた考えだと思っている。")
  JpnArray1.append("僕は遠い郊外からわざわざ通勤しなければいけない。もううんざりだ！")
  JpnArray1.append("余生は自分の理想の追求に費やしたい。")
  JpnArray1.append("現役を引退した後、テレサは孤児の世話に一身を捧げた。")
  JpnArray1.append("困っている子供たちのために、私たちは募金活動に協力した。")
  JpnArray1.append("その慈善団体には、およそ２０億円の寄付をした人物の名前が付けられている。")
  JpnArray1.append("彼の自叙伝が今日発売され、午前中に完売した。")
  JpnArray1.append("高潔な人物だと度々称されるテッドが市長に立候補する。")
  JpnArray1.append("その候補者は選挙結果に落胆した。")
  JpnArray1.append("市議会は具体的な問題にもっと焦点を当てるべきだ。")
  JpnArray1.append("年金生活が厳しい生活を強いられているというのは事実です。")
  JpnArray1.append("このデータは除外した方がいい。正確と言うにはほど遠いものだ。")
  JpnArray1.append("私たちは政治家というと偽善を連想しがちだ。")
  JpnArray1.append("彼らの一番の関心事は私たちの生活水準を高めることではなく、私たちから搾取することだ。")
  JpnArray1.append("その男はかつて保守政党に対して支配的影響力を及ぼしていたが、今では彼の力も弱まっている。")
  JpnArray1.append("報道担当者は調査中ですと言って一切のコメントを拒否した。")
  JpnArray1.append("背後で糸を引いている人物がいると警察は言っている。")
  JpnArray1.append("役員たちは何らかの見返りを期待して官僚たちを料亭、すなわち、高級な日本料理店で接待した。")
  JpnArray1.append("彼の秘書は機密情報はいっさい漏らしていないと明言した。")
  JpnArray1.append("クビになるのが怖いから、雇用主にあえて逆らおうとする人は誰一人としていない。")
  JpnArray1.append("彼は自分の尊厳を守るために将来有望な経歴を犠牲にした。")
  JpnArray1.append("自分の運命に甘んじるくらいなら自殺した方がましだ。")
  JpnArray1.append("毒物を飲んで自殺をしようとした直前に彼は思いとどまった。")
  JpnArray1.append("その曖昧な噂は嘘だと分かった。だがそれでも、多少の疑いはまだ残る。")
  JpnArray1.append("ある政府高官が企業から賄賂を受け取った容疑をかけられている。しかし、逮捕するには証拠が不十分だ。")
  JpnArray1.append("そのプロジェクトの責任者であったジェイソンが、汚職に手を染めた理由で解任された。")
  JpnArray1.append("私の知る限り、彼はその詐欺の企みには関与していません。")
  JpnArray1.append("関連書籍の山を調べていくうちに、彼らは真実をつかんだ。")
  JpnArray1.append("彼らが十数年にわたって違法取引を隠ぺいしたことが、公判中に明らかになった。")
  JpnArray1.append("刑事はその場で、彼の証言を一言一句正確に書き取った。")
  JpnArray1.append("生まれて初めて良心の呵責を感じましたが、そうする以外にその場をしのぐ方法はありませんでした。")
  JpnArray1.append("昨日の夜に見た生々しい悪夢がまだ頭から離れない。")
  JpnArray1.append("概して、記者というものは個人のプライバシーを侵害することにためらいを感じない。")
  JpnArray1.append("著者は何度も何度も原稿を手直しした。")
  JpnArray1.append("他人の過ちを指摘することにかけては、彼の右に出るものはいない。")
  JpnArray1.append("概して、エリートたちは批判に対して鈍感だ、")
  JpnArray1.append("ある大衆紙に彼は麻薬常用者だと暴露され、彼の評判はほとんど地に落ちた。")
  JpnArray1.append("彼らはその防衛計画をあらゆる面から検討し、多数の問題個所を指摘した。")
  JpnArray1.append("我々は、誰であろうとテロ活動に携わる者に寛容でいるつもりはない。")
  JpnArray1.append("悪名高い反乱兵はついに捕えられ、留置所に身柄を拘束された。")
  JpnArray1.append("暴動を鎮圧するために、直ちに軍隊が派遣された。")
  JpnArray1.append("私たちは暴力に頼るのではなく、理性に訴えるべきだ。")
  JpnArray1.append("当分の間は柔軟な戦術を取ってみてはどうでしょう。")
  JpnArray1.append("軍は全領土を占領することに成功した。")
  
  
  EngArray1[0] = "We must respect the will of the individual."
  EngArray1.append("Take it easy. I can assure you that everything will turn out fine.")
  EngArray1.append("Let go of your negative outlook on life. Always maintain a positive attitude.")
  EngArray1.append("You should be fair to everyone regardless national origin, gender, or creed.")
  EngArray1.append("Equality is guaranteed by the Constitution.")
  EngArray1.append("He leaned against the pillar and gazed at the Statue of Liberty.")
  EngArray1.append("A woman passed by me giving off a subtle scent of perfume. It reminded me of my ex-girlfriend.")
  EngArray1.append("Natto smells awful but tastes terrific.")
  EngArray1.append("I'm soaked with sweat. Stand back! You stink. Take a shower.")
  EngArray1.append("Bob was so beside himself that he could scarcely tell fact from fiction.")
  EngArray1.append("His new novel, which combines prose with his gift for poetry, is going to be published.")
  EngArray1.append("An up-to-date edition of the encyclopedia will come out next month.")
  EngArray1.append("Ms. Yamada translated the fascinating fairy tale into plain Japanese.")
  EngArray1.append("The following passage is quoted from a well-known fable.")
  EngArray1.append("Are you familiar with contemporary literature? I know next to nothing about it.")
  EngArray1.append("At times I confuse curve with carve.")
  EngArray1.append("Don't be shy. Your pronunciation is more or less correct.")
  EngArray1.append("This article contains tips for those who are eager to increase their vocabulary.")
  EngArray1.append("His latest works are on display at the city hall. They are fabulous beyond description.")
  EngArray1.append("Could you move over a little? Oh, sorry. I didn't realize I was taking up so much space.")
  EngArray1.append("What's this ugly object? This is a piece of abstract art!")
  EngArray1.append("I begged Richie to lend me a hundred bucks, but he shook his head, saying, I'm broke, too.")
  EngArray1.append("I'm apt to buy things on impulse whenever something is on sale. So am I.")
  EngArray1.append("As it is, ordinary people cannot afford to purchase such luxuries.")
  EngArray1.append("As we anticipated, the unemployment rate has risen three quarters in a row.")
  EngArray1.append("I have to cut down on my expenses, so from now on, I'm going to keep track of them on a daily basis.")
  EngArray1.append("In any case, the union has to compromise to a certain extent.")
  EngArray1.append("Competent mechanics are in great demand, so they earn decent wages.")
  EngArray1.append("The president announced a concrete plan to carry out welfare reform.")
  EngArray1.append("His policy will no doubt lead to dismal consequences. It needs a thorough review.")
  EngArray1.append("It goes without saying that the aging of society is inevitable.")
  EngArray1.append("Please take a look at this chart. It indicates that juvenile delinquency is on the increase at an alarming rate.")
  EngArray1.append("In many business districts, there are a lot of vacant lots which have been for sale for years.")
  EngArray1.append("The population density in the metropolis is gradually decreasing.")
  EngArray1.append("In all likelihood, the birthrate will continue to decline steadily for years to come.")
  EngArray1.append("The power plant supplies the remote county with electricity.")
  EngArray1.append("You are not allowed to operate this device without permission.")
  EngArray1.append("In fact, the inhabitants have been exposed to radiation.")
  EngArray1.append("One cannot emphasize too much the potential danger of nuclear energy.")
  EngArray1.append("For years the press overlooked the problem. But now, if anything, they are making too much of it.")
  EngArray1.append("As well as cultivating grain, the farmer runs a grocery store.")
  EngArray1.append("The research institute was established in the late 1960s.")
  EngArray1.append("Why don't you consult Starr in person? He's by far the most prominent attorney around here.")
  EngArray1.append("I'll write it down just in case, because I have a bad memory.")
  EngArray1.append("The lawyer recommended that his client take legal action against the insurance company.")
  EngArray1.append("They are entitled to be compensated for their injuries.")
  EngArray1.append("So far, no less than 200 people have died of the flu epidemic.")
  EngArray1.append("The effect of those pills is intense but brief.")
  EngArray1.append("He has a habit of biting his nails. It's absolutely disgusting.")
  EngArray1.append("My grandma strained her back when she bent down to hug my son.")
  EngArray1.append("If you have a stiff neck, try an herbal remedy.")
  EngArray1.append("Medical breakthroughs have brought about great benefits for humanity as a whole.")
  EngArray1.append("We can't apply cloning techniques to cattle, let alone human beings. It's forbidden.")
  EngArray1.append("Whales are classified as mammals.")
  EngArray1.append("The theory of evolution is beyond the reach of my imagination.")
  EngArray1.append("The biologist is proud of his historic discovery and doesn't mind boasting about it.")
  EngArray1.append("On ethical grounds, they are opposed to so-called gene therapy.")
  EngArray1.append("The initial symptoms of the disease are fever and a sore throat.")
  EngArray1.append("The structure of the brain is complex.")
  EngArray1.append("Owing to illness, some representatives were absent from the annual conference.")
  EngArray1.append("Little by little, my son-in-law is recovering from stomach cancer, and now he is in good spirits.")
  EngArray1.append("This is fake, isn't it? Hey, it's a genuine antique. No way!")
  EngArray1.append("Anything else? That's it. For here or to go? To go.")
  EngArray1.append("How much is this rug? $100 including tax. OK, I'll take it.")
  EngArray1.append("I don't think those pants look good on you. Try these on. They're really in now.")
  EngArray1.append("He got out of the cab in haste, saying, Keep the change.")
  EngArray1.append("Delivery service is available to our customers for a slight extra charge.")
  EngArray1.append("It's on me. No. You treat me every time we eat out. Well, okay. Let's split the check then.")
  EngArray1.append("While I was hanging out at the mall, I ran into Ken.")
  EngArray1.append("I was short of cash, so I withdrew the $100 that I had deposited in my bank account last week.")
  EngArray1.append("On her way home she was robbed of her purse.")
  EngArray1.append("That's odd! Tell me how it happened. I'll explain it to you later.")
  EngArray1.append("My parents gave me a 6 pm curfew as a punishment because I broke my promise.")
  EngArray1.append("As the proverb goes, The end justifies the means.")
  EngArray1.append("Now that I've found that there's no one to turn to, I'll have to stand on my own two feet.")
  EngArray1.append("The chairman cut me off, saying Time to wind things up. Let's take a vote.")
  EngArray1.append("We exchanged frank opinions in the meeting, but consensus is yet to be reached regarding this matter.")
  EngArray1.append("Do you agree or disagree with him? I'm on his side.")
  EngArray1.append("Strictly speaking, his view differs somewhat from mine.")
  EngArray1.append("Could you go over it again? I couldn't make out what you were getting at.")
  EngArray1.append("No one backed me up at first, but eventually I talked everyone into going along with my plan.")
  EngArray1.append("I admire your perseverance, courage and wisdom. You flatter me!")
  EngArray1.append("In making a decision, I rely not on logic but on instinct.")
  EngArray1.append("He came up with an ingenious, sensible solution and immediately put it into practice.")
  EngArray1.append("From an objective viewpoint, the former is inferior to the latter.")
  EngArray1.append("Your idea sounds marvelous in theory, yet I don't think it will work in practice.")
  EngArray1.append("We expected him to defeat his opponent, but he failed to live up to our expectations.")
  EngArray1.append("Ironically, despite their best endeavors, their mission resulted in complete failure.")
  EngArray1.append("Her genius makes up for her lack of firsthand experience.")
  EngArray1.append("She possesses a great capacity for overcoming any obstacle.")
  EngArray1.append("Without your solid support, the deal would have fallen through. I'm grateful to you.")
  EngArray1.append("Bringing flammable items into the cabin is prohibited.")
  EngArray1.append("Our flight to Vienna was delayed on account of a minor accident.")
  EngArray1.append("The plane blew up and plunged into the ocean, killing all the people on board.")
  EngArray1.append("They are working around the clock looking into the cause of the crash.")
  EngArray1.append("Unfortunately, few passengers survived the catastrophe.")
  EngArray1.append("The aviation expert analyzed the statistics in detail.")
  EngArray1.append("On behalf of all the staff, I'd like to express our sympathy for the victims.")
  EngArray1.append("In a sense, he is to blame for the disaster.")
  EngArray1.append("The vehicles are inspected for defects every three months.")
  EngArray1.append("I was amazed to see that our utility bills came to so much!")
  EngArray1.append("Turn the faucet off! mom yelled in a rage.")
  EngArray1.append("Tighten the lid so the food doesn't go bad.")
  EngArray1.append("Can I borrow your scissors? Sure, here you are.")
  EngArray1.append("You can substitute some transparent glue for a needle and thread.")
  EngArray1.append("I dyed this fabric and it shrank.")
  EngArray1.append("I'm getting rid of this leather jacket because it's worn out at the elbows.")
  EngArray1.append("Add some flour to the mixture and stir it until it becomes thick.")
  EngArray1.append("What should we do with the leftovers? Keep them in the fridge for now. I'll heat them in the microwave later.")
  EngArray1.append("I could have laid out all that money on a new PC, but on second thought I decided to put some aside for a rainy day.")
  EngArray1.append("A cell phone has become something of a necessity, and I can't do without one.")
  EngArray1.append("No sooner had I sat back and relaxed than my wife asked me to do the chores.")
  EngArray1.append("She laid the baby down and lay down beside him.")
  EngArray1.append("Put this stuff away! It's in the way.")
  EngArray1.append("When the kids made believe they were dinosaurs, they were scolded by their mother.")
  EngArray1.append("After he bumped into the shelf, the priceless china fell and shattered into fragments.")
  EngArray1.append("Can you keep an eye on my kids for a while? I need to pick up Ken. No problem.")
  EngArray1.append("Our neighbor told us off for making a mess in his yard.")
  EngArray1.append("Dolly resembles her big sister in every way. You can't tell them apart.")
  EngArray1.append("As a rule, twins have a lot in common.")
  EngArray1.append("I'm tired of doing the dishes, doing the laundry, and so on!")
  EngArray1.append("My favorite pastime is strolling along the shore. It's pleasant.")
  EngArray1.append("I'm exhausted! Let's take a break in the shade. Why not?")
  EngArray1.append("Bob, this vending machine is out of order. Oh no! I'm dying of thirst!")
  EngArray1.append("He fainted with hunger and fatigue, but came to after a while.")
  EngArray1.append("The auditorium was empty except for a single piece of furniture.")
  EngArray1.append("Any apartment will do as long as the rent is low. I'm not particular about it.")
  EngArray1.append("His sixty-year-old cousin inherited a piece of real estate by a lake.")
  EngArray1.append("So much for small talk. Let's get down to business.")
  EngArray1.append("Lucy resented the aggressive salesman trying to make her sign the contract.")
  EngArray1.append("There are a number of factors discouraging us from investing in stocks.")
  EngArray1.append("Japan imports various raw materials and exports manufactured goods.")
  EngArray1.append("In the course of its economic development, Japan has abandoned its traditional values.")
  EngArray1.append("The world is faced with an unprecedented crisis.")
  EngArray1.append("In short, the purpose of the regulations is to protect domestic industries.")
  EngArray1.append("In order to keep up its competitiveness in the world, Japan must undertake sweeping deregulation in earnest.")
  EngArray1.append("We cannot turn out back on desperate people who are at risk.")
  EngArray1.append("The parliament decided to provide developing countries with financial aid.")
  EngArray1.append("Some say the British monarchy should be abolished. What do you think?")
  EngArray1.append("They sought shelter from the attack but found no place to hide.")
  EngArray1.append("There's little prospect that the two countries will make significant progress in disarmament.")
  EngArray1.append("The negotiations are under way. Before long, they will enter a crucial phase.")
  EngArray1.append("The slaves were anxious to alter their destinies.")
  EngArray1.append("The aristocrats abused their privileges to their hearts' content.")
  EngArray1.append("The revolution in itself, bore no fruit, after all.")
  EngArray1.append("Bob cut in on our conversation, saying, I'm against it! But everybody ignored him.")
  EngArray1.append("We skipped his turn on purpose.")
  EngArray1.append("He saw someone being bullied, but he turned a blind eye.")
  EngArray1.append("When Nick and I cheated on an exam, I was suspended from school. As for Nick, he got away with it.")
  EngArray1.append("They are hostile to Richard because they are jealous of his wealth and status.")
  EngArray1.append("I hate him! He behaves as if he were somebody.")
  EngArray1.append("In spite of our compliments, he frowned and turned away. He was so rude!")
  EngArray1.append("He claimed that the enormous property was at his disposal.")
  EngArray1.append("The more stubborn you are, the more isolated you become.")
  EngArray1.append("Don't beat around the bush! What am I supposed to do? Just wait and see. Time will tell.")
  EngArray1.append("Please hand in your assignment via e-mail no later than 5:00 PM on June 10.")
  EngArray1.append("Joe is anything but diligent. That's why he flunked math again.")
  EngArray1.append("His thesis doesn't make sense. To begin with, the theme is obscure.")
  EngArray1.append("His essay was concise and to the point.")
  EngArray1.append("How are you going to deal with this complicated problem? Leave it to me! It's a piece of cake.")
  EngArray1.append("Nick, I want you to look this over before I turn it in. Sorry, but I have my hands full right now.")
  EngArray1.append("What if I don't meet the deadline? I bet he'll get mad at you!")
  EngArray1.append("Your summary leaves nothing to be desired apart from the terrible handwriting.")
  EngArray1.append("You ought to think over whether the premise is valid or not.")
  EngArray1.append("Above all, scientific terms call for precise definitions.")
  EngArray1.append("First of all, learn the formula by heart.")
  EngArray1.append("To calculate the volume, multiply the length by the width by the depth.")
  EngArray1.append("Tiny cracks were found in the bottom of the barrel.")
  EngArray1.append("This chapter will focus on the concepts of geometry.")
  EngArray1.append("Phil is much more interested in academic subject than in practical skills.")
  EngArray1.append("Something's gone wrong with this microscope. I need to have it repaired. Let me see it. Maybe I can fix it.")
  EngArray1.append("What is an instrument? For instance, a gauge, such as a thermometer or a barometer.")
  EngArray1.append("The minute particles are barely visible to the naked eye.")
  EngArray1.append("Muscle tissue consists of a vast number of cells.")
  EngArray1.append("This substance is mostly composed of hydrogen and oxygen.")
  EngArray1.append("The exact temperature is 22.68 degrees Celsius.")
  EngArray1.append("Naomi likes to show off her perfect figure. I wish I were thin like her. I envy her. You could go on a diet.")
  EngArray1.append("I fell in love with Naomi at first sight. Three months later, I took a chance and proposed to her, but she turned me down.")
  EngArray1.append("I met the man by chance. He's gentle and smart. What's more, he's single!")
  EngArray1.append("His nephew was brought up to be modest and considerate.")
  EngArray1.append("I introduced Bob to my folks, and they took to him at once.")
  EngArray1.append("People should be judged not so much by how they look as by who they are.")
  EngArray1.append("It's not your title that counts. That's for sure! exclaimed Bob.")
  EngArray1.append("As a self-made man put it, A man of vision will make good in the end.")
  EngArray1.append("Keep in mind that youth is not eternal.")
  EngArray1.append("I can't figure out why on earth everybody feels so much contempt for Bob!")
  EngArray1.append("I can't help laughing at him because he keeps on making stupid mistakes. He'd be the last person to learn his lesson.")
  EngArray1.append("To make matters worse, he isn't even conscious of annoying us.")
  EngArray1.append("Since I was in a hurry, I put my gloves on inside out by mistake.")
  EngArray1.append("Dave is fat and clumsy. When he leaped over the shallow stream, he stumbled and twisted his ankle.")
  EngArray1.append("I'm scared of heights. You're a coward!")
  EngArray1.append("The passive man seldom, if ever, expresses himself in public.")
  EngArray1.append("Nick convinced me that all superstitions are irrational.")
  EngArray1.append("I tremble with fear at the thought of an injection.")
  EngArray1.append("Since Bob is lazy at heart, he frequently neglects his duties.")
  EngArray1.append("While Bob was at work, Jennifer was at home absorbed in silly soap operas.")
  EngArray1.append("Bob likes cartoons, but I don't think much of them. As a matter of fact, they're boring.")
  EngArray1.append("It occurred to me that he was holding something back, because he wouldn't look me in the eye.")
  EngArray1.append("When her patience gave out, she grabbed his collar and swore at him.")
  EngArray1.append("I must admit we quarrel every now and then, but generally we're on good terms with each other.")
  EngArray1.append("Do you mind if I stop by your house? No, not at all. Be my guest!")
  EngArray1.append("Hold on. I'll be right back. Don't hang up!")
  EngArray1.append("I can't put you up. For one thing, my dad drops in on me from time to time.")
  EngArray1.append("While Jennifer was standing still, Bob was pacing back and forth along the sidewalk.")
  EngArray1.append("Let's make up, Lisa. Stop taking me for granted! We're through for good this time. I mean it!")
  EngArray1.append("Come on! Don't get so emotional, Lisa. I didn't mean to hurt you. Let's talk it over.")
  EngArray1.append("You betrayed me! Please forgive me. How can I make it up to you? I'll get even!")
  EngArray1.append("You should confess your sins rather than conceal them.")
  EngArray1.append("Keep your word; otherwise you'll end up losing face.")
  EngArray1.append("Bob sticks to his moral principles and believes that honesty pays off in the long run.")
  EngArray1.append("Cheer up! You couldn't help it. I did my best. I know. Don't dwell on the past. You can start over!")
  EngArray1.append("Jane, please do me a favor and give me a ride to Times Square. I wish I could, but I'm tied up right now.")
  EngArray1.append("As usual, Mike turned up on time. He's very punctual.")
  EngArray1.append("The other day I ran out of gas in the middle of a busy Interstate.")
  EngArray1.append("A truck driving ahead of me skidded, turned over, and scattered its load all over the road.")
  EngArray1.append("He recalled that a collision had been avoided by sheer luck.")
  EngArray1.append("In case of an emergency, get in touch with my agent right away.")
  EngArray1.append("Jane, where are you heading? I think we're lost. We went in the wrong direction. Damn! Pull over!")
  EngArray1.append("My rusty Ford broke down, obstructing the intersection.")
  EngArray1.append("There are so many fine scratches and dents on its surface, it's no use polishing it.")
  EngArray1.append("Hey, we're stuck in a traffic jam! Chill out, Joe. Let's take a shortcut! We'll get there in time.")
  EngArray1.append("I've got a flat tire. Can you give me a hand? I'd be glad to.")
  EngArray1.append("The ambulance went out of control and came close to running over a pedestrian.")
  EngArray1.append("He contends that primitive life once existed on Mars.")
  EngArray1.append("The crew is busy preparing for the voyage into outer space.")
  EngArray1.append("They conducted a series of experiments under zero gravity.")
  EngArray1.append("Many astronomers assume that the universe will expand infinitely.")
  EngArray1.append("The astronauts were greeted with spontaneous applause.")
  EngArray1.append("A fund was set up with a view to preserving our endangered planet.")
  EngArray1.append("The massive flood paralyzed the local transportation network.")
  EngArray1.append("The equator divides the globe into two hemispheres.")
  EngArray1.append("I think it's cruel to trap animals for fur coats.")
  EngArray1.append("The organization plays a principal role in wildlife conservation.")
  EngArray1.append("Many fragile species are on the verge of extinction.")
  EngArray1.append("The prolonged drought did severe damage to the crops.")
  EngArray1.append("Tropical rain forests are quickly disappearing on a global scale. In part, it's due to acid rain.")
  EngArray1.append("It is said that global warming is directly related to carbon dioxide emissions.")
  EngArray1.append("The destruction of the ozone layer affects the environment.")
  EngArray1.append("The committee called on all nations to work side by side to curb air pollution.")
  EngArray1.append("A satellite was launched into orbit to monitor melting glaciers.")
  EngArray1.append("The ecologist has warned us time and again that petroleum is not only a blessing but also a curse.")
  EngArray1.append("The continent is abundant in fossil fuels.")
  EngArray1.append("The region is relatively rich in mineral resources.")
  EngArray1.append("Wheat accounts for approximately two-thirds of agricultural production in the area.")
  EngArray1.append("Fertile soil is indispensable for a good harvest.")
  EngArray1.append("A humid climate is characteristic of the peninsula.")
  EngArray1.append("The active volcano erupts at regular intervals.")
  EngArray1.append("The Panama Canal connects the Atlantic with the Pacific.")
  EngArray1.append("The geographical features here are similar to those of our prefecture.")
  EngArray1.append("More often than not, famine is accompanied by plague.")
  EngArray1.append("A devastating earthquake hit the state capital, leaving tens of thousands of residents homeless.")
  EngArray1.append("Watch out! The ceiling is giving way!")
  EngArray1.append("The weather forecast says the typhoon is likely to accelerate and approach the coast.")
  EngArray1.append("It's still up in the air whether the game will be called off or not. So what? It makes no difference to me.")
  EngArray1.append("It's foggy, isn't it? It sure is. But chances are it'll clear up later on.")
  EngArray1.append("For the most part, modernization is identified with westernization.")
  EngArray1.append("Urban culture appears to be attractive to many people, in particular, to younger people.")
  EngArray1.append("AI stands for artificial intelligence.")
  EngArray1.append("Household appliances are becoming more convenient day by day.")
  EngArray1.append("My income is not adequate to provide for my family of four, but we have to make the best of it.")
  EngArray1.append("The popularity of a website depends on its content.")
  EngArray1.append("You've got to keep up with it. Once you fall behind, it's hard to catch up.")
  EngArray1.append("As technology rapidly advances, it's tough to keep pace with it.")
  EngArray1.append("More and more people are rushing to make use of the interactive nature of the medium.")
  EngArray1.append("Innovation has something to do with the ability to notice unusual phenomena.")
  EngArray1.append("A bunch of other companies are imitating our excellent methods.")
  EngArray1.append("The once desolate valley was transformed into a thriving hub of hi-tech business.")
  EngArray1.append("Although there's still plenty of room for improvement, his invention is superior to conventional equipment in every respect.")
  EngArray1.append("The strength of the firm is attributed to its unique and future-oriented strategies.")
  EngArray1.append("SONY has integrated a wide range of functions into this cool gadget. It's catching on from coast to coast.")
  EngArray1.append("This tool comes in handy, so I always keep it close at hand.")
  EngArray1.append("In general, consumers prefer quantity to quality. It's the other way around today.")
  EngArray1.append("Obviously, the advertisement is aimed at teenagers.")
  EngArray1.append("The factory now under construction will assemble 1,000 VCR units per day.")
  EngArray1.append("Efficient machinery replaced manual labor.")
  EngArray1.append("In those days, the gigantic corporation had a virtual monopoly over internal commerce.")
  EngArray1.append("With restrictions removed, thousands of new enterprises have come into being.")
  EngArray1.append("As a result of his ridiculous venture, he is in danger of going bankrupt.")
  EngArray1.append("Compared to the previous year, business is looking up in terms of sales. However, we haven't made any profit yet.")
  EngArray1.append("I'm going to be transferred to an overseas branch. Oh, I'll miss you. Please drop me a line.")
  EngArray1.append("While he was away on business, his wife gave birth to a baby boy.")
  EngArray1.append("Apparently, Nick wasn't willing to take on the task because it would just add to his burdens.")
  EngArray1.append("Bob had intended to take her out tonight, but he had to work overtime.")
  EngArray1.append("Please estimate the losses by Friday at the latest. I'll manage it somehow.")
  EngArray1.append("Nick, I'm counting on you. OK, I'll see to it. Thanks, I appreciate it. Don't mention it.")
  EngArray1.append("He pretends to be enthusiastic when his boss is around.")
  EngArray1.append("He got promoted at the expense of his colleagues. He should be ashamed of himself.")
  EngArray1.append("As the recession set in, temporary employees were laid off one after another.")
  EngArray1.append("Nowadays, many people are out of work against their will. Who is responsible for that?")
  EngArray1.append("I've gotten pessimistic, and I'm worried about something I would never have been concerned about before.")
  EngArray1.append("Today, even white-collar workers are confronted with great hardships.")
  EngArray1.append("The authorities are striving in vain to stabilize the currency.")
  EngArray1.append("We've come to the conclusion that nothing is more urgent than reducing Japan's huge deficit.")
  EngArray1.append("The questionnaires were distributed at random.")
  EngArray1.append("All you have to do is fill in the blanks below. (Please print in black or blue ink.)")
  EngArray1.append("In addition to a 10% discount, you can pick out an optional excursion for free.")
  EngArray1.append("Round-trip fares to each destination are as follows.")
  EngArray1.append("Don't forget to confirm your reservation in advance. I won't.")
  EngArray1.append("Be sure to check in at least 45 minutes prior to departure time.")
  EngArray1.append("I attached my nametag to my baggage, but it soon came off.")
  EngArray1.append("On average, these packages weigh two pounds.")
  EngArray1.append("This plastic garbage bag is free of hazardous chemicals.")
  EngArray1.append("This flashlight is getting dim. It needs new batteries.")
  EngArray1.append("Excuse me. How often do the shuttle buses run to downtown New York?")
  EngArray1.append("The motel can accommodate as many as 400 guests.")
  EngArray1.append("This suite is three times larger than my condominium.")
  EngArray1.append("Littering in this facility is subject to a maximum fine of $500.")
  EngArray1.append("That restaurant is always packed. We'd better make a reservation beforehand.")
  EngArray1.append("Sorry to interrupt your meal but I'd like a word with you in private. Can I get back to you later?")
  EngArray1.append("The cook was astonished at his incredible appetite.")
  EngArray1.append("What's going on down there? I'm curious. I have no idea.")
  EngArray1.append("Excited fans were hanging around the rear exit hoping to catch a glimpse of Michael.")
  EngArray1.append("On encountering the celebrity, they asked for his autograph.")
  EngArray1.append("Whenever I go abroad, I suffer from jet lag and diarrhea.")
  EngArray1.append("I feel sort of dizzy and I feel like throwing up. You look pale!")
  EngArray1.append("Take some aspirin. It will cure you of your headache in no time.")
  EngArray1.append("I'm afraid I'm coming down with something. You should take a day off.")
  EngArray1.append("Some of the ingredients in this beverage are harmful, especially if you are pregnant.")
  EngArray1.append("Good nutrition is vital for an infant's growth.")
  EngArray1.append("Moderate exercise stimulates the circulation of the blood.")
  EngArray1.append("My physician advised me to refrain from alcohol for the time being.")
  EngArray1.append("I do want to get into shape and lose some weight, so I go swimming every morning.")
  EngArray1.append("He caught a nasty cold because he stayed up late last night.")
  EngArray1.append("The surgeon persuaded him to undergo an organ transplant.")
  EngArray1.append("Since our father is bedridden, we take turns looking after him.")
  EngArray1.append("Our hypothesis is that eating excessive amounts of junk food contributes to early mortality.")
  EngArray1.append("The government did not take appropriate measures to prevent the infection from spreading.")
  EngArray1.append("The minister was obliged to resign from the Cabinet.")
  EngArray1.append("Many people regard the current compulsory education system as being obsolete.")
  EngArray1.append("Many people encouraged me to fulfill my ambitions.")
  EngArray1.append("To make his dreams come true, he dropped out of school and made his way to Tokyo.")
  EngArray1.append("What do you do? I'm a college student, a freshman at Harvard. What's your major? Philosophy.")
  EngArray1.append("Tuition will be raised by nearly ten percent as of April 1, 2001.")
  EngArray1.append("I'm of two minds whether to apply for the scholarship or not. Give it a try!")
  EngArray1.append("As soon as he graduated from Keio University, he took over his family's business.")
  EngArray1.append("You aren't cut out for the military because of its rigid discipline.")
  EngArray1.append("I am determined to make a living as a playwright at all costs.")
  EngArray1.append("As he grew up, he learned to put things in perspective.")
  EngArray1.append("Conformity is an essential element of our homogeneous community.")
  EngArray1.append("I'd rather go my own way than toil away for a company. Trying to fit into a mold gets me nowhere!")
  EngArray1.append("Tom takes after his uncle in personality. I mean, he is obstinate by nature. He never gives in.")
  EngArray1.append("When the time is ripe, be bold and go for it! I'll stand by you.")
  EngArray1.append("I'll stand up for what I believe in and won't yield to any threats.")
  EngArray1.append("If only I could conquer my weaknesses! It's up to you.")
  EngArray1.append("You should make the most of this rare opportunity to demonstrate your talent.")
  EngArray1.append("You won't let me down. I have great faith in you. You can make it!")
  EngArray1.append("The spectators were moved by her graceful performance.")
  EngArray1.append("In 1995, Ando received architecture's most prestigious award.")
  EngArray1.append("In the face of adversity, Mike accomplished an extraordinary feat. He deserves praise.")
  EngArray1.append("The audience was impressed by his eloquent lecture.")
  EngArray1.append("From a humble background, John achieved worldwide fame.")
  EngArray1.append("He accumulated a tremendous fortune during the postwar era.")
  EngArray1.append("He used to be well off and generous, but now he lives from hand to mouth.")
  EngArray1.append("Nick is by no means satisfied with the reward. He is selfish and greedy.")
  EngArray1.append("You owe me $200 altogether, Bob. When are you going to pay me back? I'm sorry. I'm hard up. There you go again!")
  EngArray1.append("To Brian's surprise, his debt amounted to a considerable sum.")
  EngArray1.append("Stop clinging to your glory days, or you'll be left behind.")
  EngArray1.append("You cannot escape from today's harsh realities, so you must adapt to them.")
  EngArray1.append("Prosperity does not last forever. In other words, it will come to an end one of these days.")
  EngArray1.append("Proper qualifications are required for the position; computer literacy is a must.")
  EngArray1.append("Enclose your resume in this envelope and submit it to the personnel department.")
  EngArray1.append("It's optimistic of you to believe that things will work out. At best there's a fifty-fifty chance.")
  EngArray1.append("Registration forms can be obtained free of charge.")
  EngArray1.append("Please give us a call now if you want to participate in the workshop!")
  EngArray1.append("For further inquiries, please feel free to contact us toll-free at 1-800-555-1212.")
  EngArray1.append("How's it going, Bob? Couldn't be better! I did well in my job interview! Good for you!")
  EngArray1.append("He gave instructions to the trainees, but they couldn't make heads or tails of them.")
  EngArray1.append("You can't do two things at one time! It's out of the question. Do them one by one.")
  EngArray1.append("Bob, don't disturb her. Mind your own business, he whispered.")
  EngArray1.append("If you persist in bothering her like that, she'll lose her temper.")
  EngArray1.append("He was so childish that he couldn't resist temptation.")
  EngArray1.append("Stop making a fuss. It really gets on my nerves! she shouted.")
  EngArray1.append("There's no point in talking back to Nick. He is a dictator, so to speak.")
  EngArray1.append("They are very polite in his presence, but actually, they always talk about him behind his back.")
  EngArray1.append("You despise Nick, don't you? On the contrary! I look up to him.")
  EngArray1.append("His constant insults aroused her anger.")
  EngArray1.append("I'm fed up with just shuffling papers and pouring coffee. I've made up my mind to quit!")
  EngArray1.append("In reality, many people have difficulty making ends meet. How can you get by on 100,000 yen a month?")
  EngArray1.append("Female clerks may well complain about their routines, which are not challenging at all.")
  EngArray1.append("Thanks to a fundamental restructuring, our surplus has swelled threefold.")
  EngArray1.append("Many people today think of loyalty to a company as an absurd notion.")
  EngArray1.append("I have to commute all the way from a distant suburb. I'm sick of it!")
  EngArray1.append("I want to spend the rest of my life pursuing my ideals.")
  EngArray1.append("After retirement, Teresa devoted herself to caring for orphans.")
  EngArray1.append("For the sake of children in need, we cooperated to collect donations.")
  EngArray1.append("The charity is named after a man who gave away some two billion yen.")
  EngArray1.append("His autobiography was released today and was sold out by noon.")
  EngArray1.append("Ted, who is often referred to as a man of integrity, is going to run for mayor.")
  EngArray1.append("The candidate was disappointed by the outcome of the election.")
  EngArray1.append("The municipal council should concentrate more on specific issues.")
  EngArray1.append("It is the case that those who live on a pension are forced to lead a hard life.")
  EngArray1.append("We should leave out this data. It's far from accurate.")
  EngArray1.append("We tend to associate politicians with hypocrisy.")
  EngArray1.append("They are primarily concerned with exploiting us, not with enhancing our living standards.")
  EngArray1.append("The man once exerted a dominant influence on the conservative party, but now his power is diminishing.")
  EngArray1.append("The spokesperson refused to make any comment, saying, It's under investigation.")
  EngArray1.append("The police say there's someone pulling strings behind the scenes.")
  EngArray1.append("The executives entertained the bureaucrats at ryotei, or exclusive Japanese restaurants, hoping for something in return.")
  EngArray1.append("His secretary flatly denied leaking any confidential information.")
  EngArray1.append("No one dares to contradict his/her employer for fear of being fired.")
  EngArray1.append("He sacrificed his promising career to retain his dignity.")
  EngArray1.append("I might as well kill myself as reconcile myself to my fate.")
  EngArray1.append("He was about to commit suicide by swallowing poison when he thought better of it.")
  EngArray1.append("The vague rumor proved to be false. Nevertheless, some skepticism lingers on.")
  EngArray1.append("A senior official is suspected of accepting bribes from a company, but there isn't sufficient evidence to arrest him.")
  EngArray1.append("Jason, who was in chrge of the project, was dismissed for corruption.")
  EngArray1.append("To my knowledge, he has not been involved in the fraud scheme.")
  EngArray1.append("They found out the truth while examining a pile of relevant documents.")
  EngArray1.append("During the trial it came to light that they had been covering up illegal transactions for decades.")
  EngArray1.append("The detective took down his testimony on the spot, word for word.")
  EngArray1.append("For the first time in my life, I felt a pang of conscience, but there was no other way out.")
  EngArray1.append("I'm still haunted by a vivid nightmare I had last night.")
  EngArray1.append("By and large, reporters don't hesitate to intrude on one's privacy.")
  EngArray1.append("The author revised his manuscipt over and over again.")
  EngArray1.append("He is second to none when it comes to finding fault with others.")
  EngArray1.append("On the whole, the elite are not sensitive to criticism.")
  EngArray1.append("When a tabloid revealed that he was a frug addict, his reputation was all but ruined.")
  EngArray1.append("They considered every aspect of the defense program and pointed out numerous flaws.")
  EngArray1.append("We will not tolerate anyone who engages in terrorism.")
  EngArray1.append("The notorious rebel was ultimately captured and confined to jail.")
  EngArray1.append("Troops were swiftly called in to put down the riot.")
  EngArray1.append("We should appeal to reason instead of resorting to violence.")
  EngArray1.append("I suggest we adopt flexible tactics for the moment.")
  EngArray1.append("The armed forces succeeded in occupying the entire territory.")
  
}
